CRM-19767 - Add case tokens to email activities
civicrm/civicrm-core pull request #10252
Opened 2017-04-26 00:11 UTC by colemanw

2017-04-26 00:21 UTC, eileenmcnaughton commented
How's about a test :-)

2017-04-26 01:46 UTC, colemanw commented
Looks like those bloated functions are untestable as-is. Would take some 
refactoring. I'll see what I can do.


On 04/25/2017 08:21 PM, Eileen McNaughton wrote:
>
> How's about a test :-)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/civicrm/civicrm-core/pull/10252#issuecomment-297202364>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/ACveINXT8XrVrG60whWcGv0v0e1FoO-Bks5rzo4ngaJpZM4NINPt>.
>

2017-04-26 05:19 UTC, eileenmcnaughton commented
CRM_Contribute_Form_AdditionalPaymentTest or CRM_Contribute_Form_Task_InvoiceTest might provide a starting point

2017-04-26 05:19 UTC, eileenmcnaughton commented
test this please

2017-05-03 17:55 UTC, tunbola requested changes

2017-05-03 17:55 UTC, tunbola commented on CRM/Utils/Token.php
>     * @param bool $escapeSmarty
There should be space here before the `@return string`

2017-05-03 17:55 UTC, tunbola commented on CRM/Contact/Form/Task/PDFLetterCommon.php
>     * @param CRM_Core_Form $form
There should be a space here also before `@throws \CRM_Core_Exception`

2017-05-03 17:56 UTC, tunbola commented
Also in addition to what was already said, would be great to have some tests for this change. :)

2017-05-03 19:43 UTC, colemanw commented on CRM/Contact/Form/Task/PDFLetterCommon.php
>     * @param CRM_Core_Form $form
Done

2017-05-03 19:43 UTC, colemanw commented on CRM/Utils/Token.php
>     * @param bool $escapeSmarty
Done

2017-05-03 19:45 UTC, colemanw commented
@guanhuan will you assign adding the test please?

2017-11-16 00:55 UTC, eileenmcnaughton commented
I'm going to close this because it needs rebasing & I think it's better to re-open once (if) rebased than to keep it open

2017-11-16 00:55 UTC, closed without merging

2017-11-17 12:44 UTC, colemanw commented
Drat. Github won't allow me to reopen a PR after rebasing it because of the force push it considers the branch to be different :(.  I've opened a new one instead.