CRM-20226: Parent Group do not inherit child group contacts
civicrm/civicrm-core pull request #10428
Opened 2017-05-27 20:37 UTC by monishdeb

2017-05-27 22:04 UTC, seamuslee001 commented
@monishdeb test failure looks related

2017-05-28 06:05 UTC, monishdeb commented
Thanks @seamuslee001 . Fixed it

2017-05-29 17:06 UTC, lcdservices commented
ran through some tests and this looks good. working as expected now.

2017-06-06 15:33 UTC, colemanw requested changes

2017-06-06 15:33 UTC, colemanw commented on CRM/Contact/BAO/Group.php
> +      $values[$object->id]['count'] = civicrm_api3('Contact', 'getcount', array('group' => $object->id));
@monishdeb are you sure this doesn't hit the `limit = 25` bug in the api3?

2017-06-06 17:49 UTC, monishdeb commented on CRM/Contact/BAO/Group.php
> +      $values[$object->id]['count'] = civicrm_api3('Contact', 'getcount', array('group' => $object->id));
@colemanw yes because on 'Manage Group' I am getting group-contact's count > 25, reason why I haven't added ```limit = 0``` option.

2017-06-06 17:53 UTC, monishdeb commented on CRM/Contact/BAO/Group.php
> +      $values[$object->id]['count'] = civicrm_api3('Contact', 'getcount', array('group' => $object->id));
I found that for 'getcount' API action, the ```limit``` is not used [here](https://github.com/civicrm/civicrm-core/blob/master/CRM/Contact/BAO/Query.php#L4410)

2017-06-06 17:54 UTC, colemanw approved these changes

2017-06-06 17:54 UTC, colemanw commented on CRM/Contact/BAO/Group.php
> +      $values[$object->id]['count'] = civicrm_api3('Contact', 'getcount', array('group' => $object->id));
Great, thanks for checking.

2017-06-06 17:55 UTC, merged