CRM-20720 CRM-20757 Fix issue where Price Options were not being sort…
civicrm/civicrm-core pull request #10542
Opened 2017-06-21 21:56 UTC by seamuslee001

…ed by weight

@agileware Folks can you give this a test and see what happens in some limited testing i have been doing seems to suggest this fixes the problem

2017-06-21 22:03 UTC, ghost requested changes
I think you spelt "weight" wrong. You've got 'wieght'.

Early morning coding, coffee time buddy!

2017-06-22 07:59 UTC, agileware commented
@seamuslee001 Hey mate, I have tested the price options re-ordering and it's working now. Cheers for that!

2017-06-22 07:59 UTC, agileware commented
(Have found another Price Options page bug, but I'll investigate that a bit more before reporting it.)

2017-06-22 08:11 UTC, seamuslee001 commented
Ping @eileenmcnaughton

2017-06-22 08:15 UTC, eileenmcnaughton commented
Looks good & both of you have looked at it so I'm happy

2017-06-22 08:15 UTC, merged

2017-06-22 08:16 UTC, eileenmcnaughton commented
@seamuslee001 do we close both JIRA now?

2017-06-22 20:45 UTC, agileware commented
@seamuslee001 @eileenmcnaughton closed JIRA and marked as fixed in 4.7.22, if that's incorrect please let me know.

2017-06-23 01:38 UTC, eileenmcnaughton commented
Thanks @agileware  - perfect!