CRM-20764 Allow clean URLs with CiviCRM on Backdrop
civicrm/civicrm-core pull request #10674
Opened 2017-07-16 16:16 UTC by herbdool

Addresses https://issues.civicrm.org/jira/browse/CRM-20764

2017-07-16 16:17 UTC, herbdool commented
@totten @colemanw here's hoping this is a fairly simple fix.

2017-07-16 21:59 UTC, seamuslee001 commented
@herbdool Herb can you rebase this branch against upstream master by doing git rebase -i upstream/master and just picking off commit e4bd329

2017-07-16 22:23 UTC, seamuslee001 requested changes

2017-07-16 22:23 UTC, seamuslee001 commented on templates/CRM/common/civicrm.settings.php.template
> +  elseif { function_exists('config_get') && config_get('system.core', 'clean_url') != 0) {
@herbdool there is also a php error here 
```
PHP Parse error:  syntax error, unexpected '{', expecting '(' in /home/jenkins/buildkit/build/core-10674-4ayju/sites/default/civicrm.settings.php on line 464
```

2017-07-17 11:14 UTC, herbdool commented
@seamuslee001 thanks, I've attempted your request and fixed the syntax error.

2017-07-17 11:18 UTC, monishdeb commented
@herbdool there's a false merge commits in the PR (see the 2nd commit). It avoid that, always rebase your current branch then rebase. Here are the steps to do  that : 
1. cd <civicrm directory>
2. Then rebase
```
git fetch upstream master
git pull --rebase upstream master
``` 
3. ```git push -f herbdool crm20764```

2017-07-17 11:33 UTC, herbdool commented
@monishdeb how about now?

2017-07-17 11:49 UTC, monishdeb commented
Perfect 😃👍

2017-08-18 18:05 UTC, laryn commented on templates/CRM/common/civicrm.settings.php.template
> +  elseif { function_exists('config_get') && config_get('system.core', 'clean_url') != 0) {
That first curly bracket should be a regular bracket:
`elseif ( function_exists('config_get') && config_get('system.core', 'clean_url') != 0) {`

2017-11-15 04:44 UTC, mlutfy commented
@monishdeb @herbdool Any reason why this hasn't been merged yet?

2017-11-15 20:50 UTC, herbdool commented
@mlutfy I'm not sure why it hasn't been merged. I think it's ready.

2017-11-15 20:53 UTC, seamuslee001 commented
Code looks good to me

2017-11-15 21:27 UTC, merged

2017-11-15 21:28 UTC, mlutfy commented
OK, taking the liberty of merging this one, based on the comments/reviews.