CRM-20910: Check permission param while retrieving participants from api
civicrm/civicrm-core pull request #10698
Opened 2017-07-19 08:14 UTC by jitendrapurohit

2017-07-19 10:54 UTC, jitendrapurohit commented
jenkins, retest this please

2017-07-19 12:53 UTC, monishdeb commented
Jenkins test this please

2017-07-19 15:04 UTC, colemanw requested changes

2017-07-19 15:04 UTC, colemanw commented on CRM/Event/BAO/Query.php
> +    }
This could be written in 1 line: 

    $checkPermission = empty($query->_skipPermission);

2017-07-20 11:27 UTC, jitendrapurohit commented on CRM/Event/BAO/Query.php
> +    }
Updated 👍

2017-07-26 04:52 UTC, jitendrapurohit commented
How do I change the status of this PR as I've updated the changed that were requested.

2017-07-28 19:25 UTC, colemanw approved these changes

2017-07-28 19:25 UTC, merged