CRM-18082 - Allow case API create to work with custom data
civicrm/civicrm-core pull request #10728
Opened 2017-07-23 10:18 UTC by mattwire

2017-07-23 10:26 UTC, mattwire commented
@colemanw @aydun Would you mind a quick review of this when you get a moment, as you are linked on the original jira issue

2017-07-24 13:24 UTC, davialexandre requested changes
@mattwire Left some inline comments. Besides that, it would be great if the PR description had details about the changes you did and their reasons. I tried to compare them to the suggestions made on the ticket's comments, but it seems you did a bit more than what is suggested there. Those details also helper reviewers to better understand what was the intent.

Finally, do you think you can add tests to this?

2017-07-24 13:24 UTC, davialexandre commented on api/v3/Case.php
> +    // check for same contact id for edit Client
Perhaps it would be better to use the comment to explain why do we need this check and the merge?

2017-07-24 13:24 UTC, davialexandre commented on api/v3/Case.php
> +    _civicrm_api3_custom_data_get($values[$caseBAO->id],TRUE,'case',$caseBAO->id);
I believe there should be spaces between each of the params here

2017-07-24 13:24 UTC, davialexandre commented on api/v3/Case.php
> +    // Creating a new case
Is this comment correct? Are we really creating a case here? If not, please use the comment to explain why do we need this

2017-07-24 13:24 UTC, davialexandre commented on api/v3/Case.php
> +function _civicrm_api3_case_create_xmlProcessor($params, $caseBAO) {
What about a docblock for this function?

2017-07-24 13:24 UTC, davialexandre commented on api/v3/Case.php
> +    'activity_date_time' => CRM_Utils_Array::value('start_date',$params),
There should be a space between the params of every `CRM_Utils_Array::value()` call here

2017-07-24 13:24 UTC, davialexandre commented on api/v3/Case.php
> +    }
I feel like this logic to get the original contact ID should be extracted to a separate function of even to a BAO method. What do you think?

2017-07-24 13:24 UTC, davialexandre commented on api/v3/Case.php
> +    elseif (empty($params['case_type'])) {
Early returns would improve this method's readability and considerably reduce the indentation level in this method

2017-08-04 13:41 UTC, mattwire commented
Pending unit test and response to @davialexandre (many of your comments are relating to existing code that I didn't modify, but you make some good observations, I'll review and update the PR appropriately).

2017-08-07 09:56 UTC, mattwire commented on api/v3/Case.php
> +  // Process params
Moved to _civicrm_api_case_format_params()

2017-08-07 09:57 UTC, mattwire commented on api/v3/Case.php
> +    civicrm_api3_verify_mandatory($params, NULL, [
Fixed

2017-08-07 09:57 UTC, mattwire commented on api/v3/Case.php
> +    // return error if modifying creator id
Removed comment

2017-08-07 09:58 UTC, mattwire commented on api/v3/Case.php
> +    $mCaseId = $origContactIds = array();
Not my code :-)  But agreed, it means merged so I've renamed to $mergedCaseId

2017-08-07 10:04 UTC, mattwire commented on api/v3/Case.php
> +      $origContactId = $origContactIds[1];
I've added a comment, again not my code, but copied from the update function.  That function returns a 1-based array, as it's used elsewhere it's not in scope for me to refactor right now!  But I've added a FIXME comment there explaining.  ```origContactId``` is an integer, ```origContactIds``` an array of contactIds, again copied from update function.

2017-08-07 10:06 UTC, mattwire commented on api/v3/Case.php
> +      }
ok, done

2017-08-07 10:07 UTC, mattwire commented on api/v3/Case.php
> +    }
Agreed. I've added a FIXME comment to that effect

2017-08-07 10:08 UTC, mattwire commented on api/v3/Case.php
> +    // check for same contact id for edit Client
Yes... Though I'm not sure myself, again it's copied from the update function

2017-08-07 10:11 UTC, mattwire commented on api/v3/Case.php
> +    // Creating a new case
We are, I don't really understand the xml stuff very well, except that cases are defined in xml files, and when creating a new one you have to read the xml file to get case params/setup the case.  I've added a comment to that effect - the code in _civicrm_api3_case_create_xmlProcessor is simply extracted code from the original api_v3_case_create function.

2017-08-07 10:12 UTC, mattwire commented on api/v3/Case.php
> +    _civicrm_api3_custom_data_get($values[$caseBAO->id],TRUE,'case',$caseBAO->id);
Done

2017-08-07 10:13 UTC, mattwire commented on api/v3/Case.php
> +function _civicrm_api3_case_create_xmlProcessor($params, $caseBAO) {
Done

2017-08-07 10:13 UTC, mattwire commented on api/v3/Case.php
> +    'activity_date_time' => CRM_Utils_Array::value('start_date',$params),
Done

2017-08-07 10:20 UTC, mattwire commented on api/v3/Case.php
> +    elseif (empty($params['case_type'])) {
Rearranged a little

2017-08-07 10:34 UTC, mattwire commented
Note: Still pending a unit test

2017-08-07 12:23 UTC, mattwire commented
@davejenx Could you do a quick review as it's in use on one of your sites :-)

2017-08-07 13:29 UTC, davejenx commented on api/v3/Case.php
> +      throw new API_Exception(ts('You cannot update creator id'));
Tiny picky point: I believe ts() isn't generally used for API exceptions. Discussed at https://chat.civicrm.org/civicrm/pl/qiotz5x6p7fxdegbiece7xhhmc . ts() isn't used for the other exceptions in this file, apart from an identical instance in civicrm_api3_case_update() which presumably this was copied from.

2017-08-07 13:58 UTC, davejenx commented
@mattwire Haven't spotted any other issues - as I understand it, the change largely consists of incorporating the relevant parts of civicrm_api3_case_update() into civicrm_api3_case_create() so that it can serve both purposes, so much of it is existing code. If the existing & new unit tests are all passing, there's nothing else that jumps out at me.@aydun made some good comments on the JIRA issue so

2017-08-07 15:20 UTC, mattwire commented on api/v3/Case.php
> +      throw new API_Exception(ts('You cannot update creator id'));
Thanks, that's now fixed

2017-08-08 03:36 UTC, colemanw commented on api/v3/Case.php
> +  }
This is an extra database hit, which we normally don't do for create operations. There is an api option called something like "force_reload" which takes care of this type of thing.

2017-08-08 10:09 UTC, mattwire commented on api/v3/Case.php
> +  }
@colemanw Ok, I've had a good look through the code for various other APIs and I can't find any reference to this.  Agreed that it's not ideal calling get again, but not sure what else I can do here to return back the customdata if it was passed in on create.

2017-08-08 14:47 UTC, colemanw commented on api/v3/Case.php
> +  }
Why is that necessary?

2017-08-09 08:33 UTC, mattwire commented on api/v3/Case.php
> +  }
I guess it's not :-)  Removed it now, all tests still passing

2017-08-09 18:23 UTC, colemanw commented on api/v3/Case.php
> +      $origContactId = $origContactIds[1];
You could use `CRM_Utils_Array::first()` so you don't have to worry about how the array is indexed.

2017-08-10 20:33 UTC, mattwire commented on api/v3/Case.php
> +      $origContactId = $origContactIds[1];
Sounds good

2017-08-14 15:18 UTC, mattwire commented
@colemanw Think this is now good to merge?

2017-08-14 17:11 UTC, merged