CRM-21015 - Fix recurring contribution creation if not checked on mai…
civicrm/civicrm-core pull request #10835
Opened 2017-08-09 11:46 UTC by jitendrapurohit

…n page

Overview
----------------------------------------
Fixes incorrect recur contribution creation when not selected on main page.

Before
----------------------------------------
Recur Contribution gets created even if it is not selected by the user.

After
----------------------------------------
works fine.

2017-08-13 13:54 UTC, eileenmcnaughton commented
@jmcclelland - is this the same as you are working on?

2017-08-13 13:55 UTC, eileenmcnaughton commented
no, I guess not

2017-08-15 15:13 UTC, highfalutin commented
reviewing this now

2017-08-15 18:18 UTC, eileenmcnaughton commented
thanks!

2017-08-17 15:57 UTC, highfalutin requested changes
The change to CRM_Contribute_Form_Contribution_Confirm fixes the issue as described in CRM-21015. 

The new test doesn't test the scenario in which I discovered the bug. I suggest the following patch:

```
diff --git a/tests/phpunit/api/v3/ContributionPageTest.php b/tests/phpunit/api/v3/ContributionPageTest.php
index e03b4bad40..5f301a849a 100644
--- a/tests/phpunit/api/v3/ContributionPageTest.php
+++ b/tests/phpunit/api/v3/ContributionPageTest.php
@@ -1205,9 +1205,9 @@ class api_v3_ContributionPageTest extends CiviUnitTestCase {
   /**
    * Test non-recur contribution with membership payment
    */
-  public function testSubmitMembershipIsSeparatePaymentNotRecur() {
+  public function testSubmitMembershipNotRecur() {
     //Create recur contribution page.
-    $this->setUpMembershipContributionPage(TRUE, TRUE);
+    $this->setUpMembershipContributionPage(FALSE, TRUE);
     $dummyPP = Civi\Payment\System::singleton()->getByProcessor($this->_paymentProcessor);
     $dummyPP->setDoDirectPaymentResult(array('payment_status_id' => 1, 'trxn_id' => 'create_first_success'));

@@ -1216,6 +1216,10 @@ class api_v3_ContributionPageTest extends CiviUnitTestCase {
       'price_' . $this->_ids['price_field'][0] => reset($this->_ids['price_field_value']),
       'id' => (int) $this->_ids['contribution_page'],
       'amount' => 10,
+      // frequency_interval and frequency_unit are included on the form
+      // whether or not 'is_recur' is selected
+      'frequency_interval' => 1,
+      'frequency_unit' => 'month',
       'billing_first_name' => 'Billy',
       'billing_middle_name' => 'Goat',
       'billing_last_name' => 'Gruff',
```

2017-08-18 09:28 UTC, jitendrapurohit commented
@highfalutin Thanks for the response, but the changes above contradicts the test I added for the separate payment. This will not check the use-case mentioned in issue description. I'm happy to add additional params `frequency_interval` and `frequency_unit`.

FWIW, the test fails if the fix part is being removed and passes after the fix is applied. So it does check the area and perform its role as a unit test.

2017-08-21 05:06 UTC, eileenmcnaughton commented
I'm going to merge this on the basis @highfalutin has verified the fix and there is test cover. I feel like @highfalutin has identified an additional test we should create & add but I think that can be done separately. How do you feel about opening a PR for an additional test based on your parameters @highfalutin ?

2017-08-21 05:06 UTC, merged

2017-08-30 16:18 UTC, highfalutin commented
@eileenmcnaughton thanks for merging and I'll open a PR for the additional test.

2017-08-30 21:37 UTC, eileenmcnaughton commented
thanks