CRM-21063 Add date to survey/details report
civicrm/civicrm-core pull request #10857
Opened 2017-08-14 18:02 UTC by adixon

Overview
----------------------------------------
As per issue, add the date field from the civicrm_activity table to make the campaign survey/details report more useful.

After
----------------------------------------
Added the date field to Columns, Sorting and Filter tabs of the report.

2017-08-21 20:37 UTC, MegaphoneJon commented
I was trying to be a good human being and do some PR review, but unfortunately I uncovered a more serious bug in the course of testing this (CRM-21089).  My time unfortunately got sucked into writing a fix for that.  I'll try to review this later in the week.

2017-08-21 21:04 UTC, adixon commented
Thanks and not to worry, you're a very good human being. Uncovering bugs is an even more noble activity.

2017-08-22 17:11 UTC, MegaphoneJon requested changes
This all looks good except for the filter bug I've mentioned in the in-line comments.

2017-08-22 17:11 UTC, MegaphoneJon commented on CRM/Report/Form/Campaign/SurveyDetails.php
> +            'type' => CRM_Utils_Type::T_DATE,
Unfortunately, this doesn't work correctly.  If you look at the developer tab, you can see they're searching by date (`20170821` to `20170821`) and not datetime (`20170821000000` to `20170821235959`).

2017-08-22 17:11 UTC, MegaphoneJon commented on CRM/Report/Form/Campaign/SurveyDetails.php
> +            'type' => CRM_Utils_Type::T_DATE,
This isn't quite right - you can't find activities on the last day of the filtered period (see below).  I tried fixing this by adding `CRM_Utils_Type::T_TIME` (which I've used to fix this bug [before](https://github.com/eileenmcnaughton/nz.co.fuzion.extendedreport/pull/57)), but it doesn't seem to have the desired effect here.

2017-08-23 21:06 UTC, adixon commented
I'm not sure I understood all your notes, but adding in T_TIME to the type in both places (fields and filters) worked in my testing, so I've added those to the PR. In my developer tab I'm now seeing sql that includes the time. Maybe you're smarter than you know?

2017-08-28 05:44 UTC, MegaphoneJon approved these changes
The latest changes fix the issue I raised last week.  This passes PR review now IMO.

2017-09-19 04:53 UTC, yashodha commented
works fine

2017-09-19 04:53 UTC, merged

2017-09-19 14:11 UTC, adixon commented
Thanks!