CRM-21098
civicrm/civicrm-core pull request #10892
Opened 2017-08-23 17:21 UTC by herbdool

Overview
----------------------------------------
Prevent Backdrop admin menu dropdowns appearing beneath the CiviCRM admin menu by hiding the Backdrop admin menu when the CiviCRM admin menu is visible and also to show the Backdrop admin menu when the CiviCRM admin is hidden.

Before
----------------------------------------
Backdrop admin menu is visible beneath the CiviCRM admin menu.

![backdrop-civicrm-menus](https://user-images.githubusercontent.com/1071483/29629177-e0fe16f2-8805-11e7-9e7f-5012f3925eda.png)

After
----------------------------------------
Backdrop admin menu is hidden when CiviCRM admin menu is visible.

Technical Details
----------------------------------------
Adds a crm.backdrop.js file for Backdrop installs.

Comments
----------------------------------------
This PR might need to be slightly updated if https://github.com/civicrm/civicrm-core/pull/10891 is merged first.

2017-08-23 23:47 UTC, colemanw requested changes

2017-08-23 23:47 UTC, colemanw commented on js/crm.backdrop.js
> +  $(document).on('crmLoad', function(e) {
You don't need this wrapper. We're already waiting for document.ready because of the `CRM.$(function()...` construct

2017-08-23 23:47 UTC, colemanw commented on js/crm.backdrop.js
> +    $('#admin-bar').css('display', 'none');
Simpler to use the `.hide()` method.

2017-08-23 23:47 UTC, colemanw commented on js/crm.backdrop.js
> +    $('#admin-bar').css('display', 'block');
Use the `.show()` method.

2017-08-23 23:47 UTC, colemanw commented on js/crm.backdrop.js
> +  $('#crm-notification-container').click(function(e) {
Better to do `$('#crm-notification-container').on('click', '#crm-restore-menu', function() {`

2017-08-23 23:47 UTC, colemanw commented on CRM/Utils/System/Backdrop.php
> +  }
Yes this function is redundant now.

2017-08-24 12:38 UTC, herbdool commented on js/crm.backdrop.js
> +  $(document).on('crmLoad', function(e) {
Fixed

2017-08-24 12:40 UTC, herbdool commented on js/crm.backdrop.js
> +    $('#admin-bar').css('display', 'none');
For some reason I don't get the same results when using .show() and .hide(). I can't get it to hide the Backdrop admin bar on page load with .hide() and using .show() on the clicks seems to interfere with the page load as well.

2017-08-24 12:41 UTC, herbdool commented on js/crm.backdrop.js
> +  $('#crm-notification-container').click(function(e) {
Thanks. I was wondering how to attach it to `#crm-restore-menu`.

2017-08-24 12:43 UTC, herbdool commented
@colemanw ready for another review. I've had mixed results with using .hide()/.show() compared to using .css() for this. I'm not sure why.

2017-08-24 15:57 UTC, herbdool commented
@colemanw oops, thanks for restoring that. It works for me locally.

2017-08-25 16:26 UTC, colemanw approved these changes

2017-08-25 16:26 UTC, merged