CRM-21105 Fixed notice error preventing dupe check for API
civicrm/civicrm-core pull request #10900
Opened 2017-08-25 10:51 UTC by Edzelopez

----------------------------------------
* CRM-21105: Undefined index for check_permission when dupe_check is enabled
  https://issues.civicrm.org/jira/browse/CRM-21105

Overview
----------------------------------------
_A brief description of the pull request. Try to keep it non-technical._

Before
----------------------------------------
_The current status. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

After
----------------------------------------
_What has been changed. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

Technical Details
----------------------------------------
_If the PR introduces noteworthy technical changes, please describe them here. Provide code snippets if necessary_

Comments
----------------------------------------
_Anything else you would like the reviewer to note_

2017-08-26 04:30 UTC, eileenmcnaughton commented
There is a actually a historical confusion between 'check_permission' & 'check_permissions'

If I grep for 'check_permission' I find 7 instances in the code base & I think we need to work through them all & fix or we might get into whack-a-mole on this

2017-08-27 17:46 UTC, colemanw requested changes

2017-08-27 17:46 UTC, colemanw commented on api/v3/Contact.php
> +    $ids = CRM_Contact_BAO_Contact::getDuplicateContacts($params, $params['contact_type'], 'Unsupervised', array(), $params['check_permissions']);
Probably the line should be

   $ids = CRM_Contact_BAO_Contact::getDuplicateContacts($params, $params['contact_type'], 'Unsupervised', array(), !empty($params['check_permissions']));

2017-08-30 07:17 UTC, Edzelopez commented
Thanks for reviewing this @eileenmcnaughton and @colemanw I will look into it.

2018-03-19 21:10 UTC, eileenmcnaughton commented
I'm going to close this & let you re-open when ready since it seems to be stalled on needing more work

2018-03-19 21:10 UTC, closed without merging