CRM-20906 Validate the extension key is of general standard
civicrm/civicrm-core pull request #10994
Opened 2017-09-19 04:41 UTC by seamuslee001

Overview
----------------------------------------
Previously there was no checking if the key passed in through the URL was a standard extension key. This adds some validation

ping @jackrabbithanna @totten @eileenmcnaughton @seanmadsen

2017-09-19 22:01 UTC, seancolsen requested changes
I have reviewed locally and requested a change via https://github.com/seamuslee001/civicrm-core/pull/5 

@seamuslee001 sorry I gave you a regex via Mattermost without fully testing it. Minor oversight here. 

Before my added commit, I was still able to reproduce the problem described in [CRM-20906](https://issues.civicrm.org/jira/browse/CRM-20906). With the addition of my latest commit I was no longer able to repro.

2017-09-19 22:02 UTC, seanmadsen commented
Thanks @seamuslee001 

This looks good to me now on all fronts. Ready to merge :white_check_mark:

2017-09-19 22:33 UTC, seanmadsen commented
Great that you've added a unit test. 

But now that you've done that I'm going to surface a nit-pick thought that I originally suppressed in my review... 

I think it would be nice to put the logic which validates an extension key into `CRM_Utils_Rule` so that it can be used elsewhere as needed. Then in the form layer, instead of `self::checkExtesnionKeyIsValid($this->_key)` we could do `CRM_Utils_Type::validate($this->_key, 'ExtensionKey')`. And the unit tests go along with `CRM_Utils_Rule`. What do you think of this approach?

2017-09-19 22:34 UTC, seamuslee001 commented
O_o that could work i guess

2017-09-19 22:37 UTC, seanmadsen commented
I general, I'd love to see us add lots of other types to `CRM_Utils_Rule`, for example, `CommaSeparatedIntegers`, so that we can move away from validating inputs simply as "string". Moving this logic there in this PR would be a step in that direction.

2017-09-19 23:07 UTC, seanmadsen commented
This looks great. Even better than before! Tested locally. Confirmed to fix issue. Code looks good. Ready to merge :white_check_mark:

2017-09-19 23:08 UTC, seancolsen approved these changes

2017-09-20 02:09 UTC, seamuslee001 commented
@colemanw i think this is right for merging now and has been tested by Sean

2017-09-20 02:17 UTC, merged

2017-09-26 03:28 UTC, eileenmcnaughton commented on CRM/Utils/Rule.php
> +  public static function checkExtesnionKeyIsValid($key = NULL) {
Too many beers when writing thish function shignature