CRM-21312 Fix display of 'Recent Items' when using a bootstrap theme
civicrm/civicrm-core pull request #11138
Opened 2017-10-14 15:18 UTC by mattwire

Overview
----------------------------------------
Before this patch, recent items is messed up on bootstrap themes. Afterwards, it is not messed up!

Before
----------------------------------------
![crm-21312_civi_recentitems_bootstrap_before](https://user-images.githubusercontent.com/2052161/31576816-1a87daf2-b0fb-11e7-9f01-c2f96180c2dc.png)

After
----------------------------------------
![crm-21312_civi_recentitems_bootstrap_after](https://user-images.githubusercontent.com/2052161/31576817-1f60cdb8-b0fb-11e7-8100-f2b7c2ea8cb7.png)

Technical Details
----------------------------------------
Tested on Bartik, Adaptivetheme, bootstrap.  Works well on all of them.

2017-10-16 01:56 UTC, seamuslee001 commented
@mattwire I'm guessing this isn't relevant to shoreditch is it because it uses its own css or will this impact shoreditch as well?

2017-10-16 01:57 UTC, seamuslee001 commented
The code looks fine and simple and i don't think it would hurt anything just would like confirmation on impact on shoreditch first

2017-10-16 02:01 UTC, eileenmcnaughton commented
@guanhuan @jmcclelland - see Shoreditch q

2017-10-16 09:56 UTC, mukeshcompucorp commented
@mattwire Padding 0 is ok but, making overflow:hidden will hide view edit option from list item, can you write counter css which allows to make it visible someway properly?

2017-10-16 14:25 UTC, jmcclelland commented
@eileenmcnaughton  I think you may have intended to ping jamie novak instead (not sure what his handle is)?

2017-10-24 13:55 UTC, mattwire commented
@mukeshcompucorp Ok, take 2.  I've wrapped the item name in a separate div so we can set overflow: hidden on that element and not affect the others.  This also has the benefit that the hardcoded string length of 25 can be removed and it looks sensible on wider displays.

![crm-21312_civi_recentitems_bootstrap_after_new2](https://user-images.githubusercontent.com/2052161/31946980-324bb14a-b8cb-11e7-93c0-79537bc9c8f2.png)
![Uploading CRM-21312_civi_recentitems_bootstrap_after_new.png…]()

2017-10-24 21:02 UTC, eileenmcnaughton commented
test this please

2017-10-26 10:41 UTC, igorpavlov commented
Please amend the overview to specify what is exactly fixed like "Fixed the layout for recent items, ... etc"

2017-10-26 10:47 UTC, igorpavlov-zz requested changes

2017-10-26 10:47 UTC, igorpavlov commented on templates/CRM/Block/RecentlyViewed.tpl
> +        <div class="crm-recentview-item">
I wonder would it be nicer to wrap a DIV into A? In that case the area of click will cover the whole div, not just a caption (not a change request but a thought)

2017-11-07 22:01 UTC, eileenmcnaughton commented
Hi guys - just trying to understand the degree of testedness / agreedness of this - I don't want to get blocked by the semantics of filing in the template - it seems agreed this is an improvement in some cases but I'm not sure if we have agreement this won't cause regressions in others.

2017-11-08 08:32 UTC, mattwire commented
@mukeshcompucorp Can you confirm you are happy with this now?

2017-11-15 04:13 UTC, mlutfy commented
I tested on a CiviCRM with an existing Bootstrap theme (which had tweaked the CSS in a not-very-clean way, so I wanted to see if it would cause problems) and it seems OK:

![civicrm-recent-items-bootstrap](https://user-images.githubusercontent.com/254741/32818323-779e32a6-c990-11e7-822c-b5eba147d0b2.jpg)

So I would be in favour of merging this - risk of breakage for existing themes seems minimal.

2017-11-15 04:49 UTC, eileenmcnaughton commented
I second @mlutfy comments & am merging - the main concern was to get Compucorp input as to whether this had any negative effects on the Shoreditch theme. An impact was identified & resolved & other comments seem to be about stylistic nuances & administrative aspects. Based on @mlutfy testing I will merge - but I suggest @guanhuan that Compucorp make a point of testing the rc / master branch

2017-11-15 04:49 UTC, merged

2018-09-16 16:31 UTC, mattwire commented
@lsmithgo I'm guessing that is an issue specific to whatever theme / theme customisation you are using.  Works fine on the standard themes (just checked again).

2018-09-16 16:55 UTC, lsmithgo commented
@mattwire I'm using the standard theme (to the best of my knowledge).  Problem only shows when the item title is long, eg when showing a Participant registered to an Event.  See the screenshot.
![capture](https://user-images.githubusercontent.com/13263543/45598815-b1fd2800-b9d9-11e8-9860-2b980808a2fe.PNG)

2018-09-16 17:14 UTC, mattwire commented
@lsmithgo Looks like a Joomla specific issue then... I suggest you open an issue at https://lab.civicrm.org/dev/core/issues making it clear it only affects Joomla, and ideally try and work out what the best fix for this might be (that doesn't stop it working properly on other CMS).