Add API parameter for fix_address
civicrm/civicrm-core pull request #11372
Opened 2017-12-05 16:21 UTC by ejegg

Change-Id: I4b59b1b1518b8f7ed24804a001d9d0fb31381b79

Overview
----------------------------------------
Expose fix_address parameter in mailing address creation API call

Before
----------------------------------------
_The current status. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

After
----------------------------------------
_What has been changed. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

Technical Details
----------------------------------------
_If the PR introduces noteworthy technical changes, please describe them here. Provide code snippets if necessary_

Comments
----------------------------------------
_Anything else you would like the reviewer to note_

2017-12-18 00:59 UTC, colemanw requested changes
Thanks for contributing! Can you please fill out the rest of the description for this PR and check the code comments I've made?

2017-12-18 00:59 UTC, colemanw commented on api/v3/Address.php
> +    'title' => 'Fix address',
Please add `ts()` around the name.

2017-12-18 00:59 UTC, colemanw commented on api/v3/Address.php
> +    'type' => CRM_Utils_Type::T_BOOLEAN,
You can add `'api_default' => TRUE` and then you won't need the additions on L79.

2017-12-18 17:23 UTC, ejegg commented
Thanks for the review @colemanw ! I've added the ts() calls and finished the PR description.

2017-12-18 21:18 UTC, ejegg commented
oops, seems like the api_default didn't actually guarantee it being set.

2017-12-18 21:21 UTC, colemanw commented
@ejegg my mistake it should have been `api.default`

2018-01-10 20:38 UTC, ejegg commented
Note: I had to add the explicit default setting back in because api.default is not consulted when an API call is made with the 'id' parameter set.

2018-01-19 20:20 UTC, ejegg commented
Hi @colemanw , I think I've made all the changes you requested. Is there something I should do here in github to formally indicate that and get rid of the 'Changes requested' status with the red 'X' mark?

2018-01-19 21:28 UTC, merged

2018-01-19 21:28 UTC, colemanw commented
This looks great. Thanks @ejegg