CRM-21712 Improve Fiscal Year date filter
civicrm/civicrm-core pull request #11592
Opened 2018-01-26 19:59 UTC by magnolia61

Overview
----------------------------------------
Many organisations use a fiscal date period other than the calendar year. Our fiscal year starts october 1st and lasts until september 30th. CiviCRM supports setting a different fiscal year. Unfortunately the data filter support for fiscal year was very limited, that is why I created this PR.  

Before
----------------------------------------
Fiscal date filters only had 'this fiscal year', 'previous fiscal year' and 'next fiscal year' 

After
----------------------------------------
I added all other relevant filters for fiscal year.

Technical Details
----------------------------------------
NA

Comments
----------------------------------------
I know there is a wish to make the whole date filter mechanism more flexible. Partly it already is because the relative filters are in an option group nowadays. But waiting for another big overhaul I think this is a good way to support fiscal year support for organisations that need it.

---

 * [CRM-21712: Improve Fiscal Year filter for reports](https://issues.civicrm.org/jira/browse/CRM-21712)

2018-01-26 20:04 UTC, magnolia61 commented
Somehow I seem to have closed the previous PR squashing the commits and trying my best. I also still figuring out where else I need to change things to make new installs and upgrades work: I mean does anything need to be added to xml/templates/civicrm_data.tpl and CRM/Upgrade/Incremental/sql/4.7.xyz.mysql.tpl ? I'm not too familiar with those mechanisms...

Also MegaphoneJon commented on the previous PR with the following:

> @magnolia61 FWIW - there's been a push not to add hardcoded filters to this function, which is already very unwieldy. I wrote a hook that allows defining relative date filters, and an extension that uses them. However, this is a hobby (i.e. unpaid) improvement for me, so it's lingered as I've gotten busy.
> 
> Would you consider looking at the review notes on #10941 and helping to get that merged as an alternative? That's some necessary cleanup to add the hook. Once that's done, adding the hook is only a couple lines of code (which I've already written).

2018-01-26 20:10 UTC, magnolia61 commented
@MegaphoneJon I am less than an amateur codes but I will try to look at  https://github.com/civicrm/civicrm-core/pull/10941 

Also in the info text of the PR I already mention that I know there is a wish to make the whole date filter mechanism more flexible. I think @joannechester pioneered in that. She made the relative filters into an option group nowadays. But waiting for another big overhaul I think this is a good way to support fiscal year support for organisations that need it and to complete the current filter range even though I know (I think already for some 3 years there is talk of an alternative).

I agree a better alternative is better, but in the meantime we as an organisation need this very basic core functionality. I's no rocket science. And we do not have resources other than to come up with this PR ;-)

So core-team, please, please knowing the whole relative date filter context please help me merge this to have a working and complete interim date filter range....

2018-01-26 20:34 UTC, MegaphoneJon commented
@magnolia61 Yes - this is the project that @joannechester and I started many years ago!  However, I want to stress that the project was much more ambitious, which is largely why it stalled.  The current approach is a) manageable, and b) already done - just waiting for merge.  It's this PR and this code I've [already written](https://github.com/MegaphoneJon/civicrm-core/commit/3f19a2b6e3e86a68b020d7013633ddb42115f739).  All that needs to happen is to get these 2 PRs merged.

I'll make you a deal - if you will help get these PRs merged, I'll convert this PR to an extension.  I honestly believe this is less work for a better solution.

2018-02-06 11:13 UTC, joannechester commented
Just wanted to set the record straight, it was @MegaphoneJon not me who made the relative date filters into an option group. I don't have the skills to do that.

2018-02-12 11:46 UTC, monishdeb requested changes
Except for the one change this PR is good to merge. Also, I have added unit test - https://github.com/civicrm/civicrm-core/pull/11663

2018-02-13 05:56 UTC, monishdeb commented
@eileenmcnaughton will it be ok to merge this PR despite a minor change, that I will do in my UT PR #11663 ?

2018-02-13 06:12 UTC, magnolia61 commented
about to add an upgrade script for adding the new relative date values to the option group. hang on.

2018-02-13 06:51 UTC, monishdeb commented
@magnolia61 seems like you simply pulled and merged the latest commits instead of rebasing. Here's the step:
```
$ git pull --rebase upstream master
$ git push -f origin CRM-21712_Improve_Fiscal_Year_Report_filters
```

Also please indicate in PR title with [WIP] that the changes aren't final.

2018-02-13 07:54 UTC, eileenmcnaughton commented
@monishdeb so the PR at the moment is quite contaminated with unrelated changes but I believe the rebased version would add a bunch more option values and also handling for some variants.

From my point of view if @MegaphoneJon & @joannechester are OK with the approach then I am since I feel they have put more thought into it than anyone else.

In terms of the bigger picture this is a fairly discrete change and the additions to the switch block don't seem like a smelly pooey pile of code smell, although I do feel like previous_2 would be better as if handling previous_n rather than specifically in the switch

2018-02-13 07:55 UTC, eileenmcnaughton commented
also probably do the upgrade script against 4.7.32 - 4.7.31 should have already been cut & if it's not merged before it is cut you'll need to redo it

2018-02-13 08:17 UTC, magnolia61 commented
messing with rebasing & commiting again ~i'm learning~ (***i know, this is not the place for a git101***)
But when I do : $ git pull --rebase upstream master
I get:
warning: 2 lines add whitespace errors.
Falling back to patching base and 3-way merge...
Auto-merging templates/CRM/Tag/Page/Tag.tpl
CONFLICT (content): Merge conflict in templates/CRM/Tag/Page/Tag.tpl
Auto-merging CRM/Member/Form/MembershipRenewal.php
Auto-merging CRM/Contact/Form/Search/Custom/Proximity.php
CONFLICT (content): Merge conflict in CRM/Contact/Form/Search/Custom/Proximity.php
error: Failed to merge in the changes.
Patch failed at 0001 CRM-21712 Improve Fiscal Year date filter
The copy of the patch that failed is found in: .git/rebase-apply/patch

And I seem to be messing and messing to get this resolved, but either I end up with 300+ files changed or with too many commits. I want to push 1 commit and 2 changed files ;-) Any tips? I can go over to thc civicrm dev chat of that's better.

2018-02-13 08:54 UTC, magnolia61 commented
ok, down to 1 commit. but still a few unrelated files

2018-02-13 09:01 UTC, mattwire commented
@magnolia61 Everyone does it slightly differently but here is what I do...

Get the upstream changes
`git fetch upstream`
Checkout local master branch
`git checkout master`
Rebase local master to match upstream/master
`git rebase upstream/master`
Force push my local master to origin/master
`git push -f`
Checkout my local branch with changes I've made
`git checkout mylocalbranch`
Rebase mylocalbranch against local master.  This is where you might need to resolve conflicts against master and you should be offered a short list of the commits you've made, which you can optionally move around/squash/drop etc.
`git rebase -i master`
Force push mylocalbranch to origin/mylocalbranch
`git push -f`

That *should* give you a clean rebase on top of current master.  If not you may need to clean up your local master branch first... try interactive rebasing master (there is probably a quicker way but this is what I do).  BE CAREFUL as you risk losing your own changes here if you've got them on the wrong branch.  An easy way to make sure they are "backed up" is to checkout a new branch from master first:
`git checkout master && git checkout -b mybackupofmaster`

Then interactive rebase on master and drop all commits that are listed so you get back to matching upstream:
`git checkout master`
`git rebase -i master`

2018-02-13 11:13 UTC, magnolia61 commented
ok, finally managed to get my stuff together (thanks @mattwire !) Thanks for your patience with me :-)

I have two questions on the upgrade: 
1) do the new option values also have to be added to xml/templates/civicrm_data.tpl for new installs?
2) I have the weight orderly set in my own install (so the new fiscal year option values are in a logical spot), how would this best be approached for the upgrade?

2018-02-13 12:59 UTC, magnolia61 commented
I think it would be great both to merge this PR for now, which will help us (and others) use fiscal year date filters, but also look into @MegaphoneJon 's PR (https://github.com/MegaphoneJon/civicrm-core/commit/3f19a2b6e3e86a68b020d7013633ddb42115f739) to make a more flexible solution for relative date filters possible.

2018-02-13 22:10 UTC, magnolia61 commented
@monishdeb is it ok like this now?

2018-02-14 03:36 UTC, monishdeb commented on CRM/Utils/Date.php
> +          case 'previous_2':
OR how about:
```php
case 'previous_2':
case 'previous_3':
  $duration = (int) str_replace('previous_', '', $relativeTerm)
  $from['Y'] = $fYear - $duration;
  $fiscalYear = mktime(0, 0, 0, $from['M'], $from['d'] - 1, $from['Y'] + $duration);
  $fiscalEnd = explode('-', date("Y-m-d", $fiscalYear));
  $to['d'] = $fiscalEnd['2'];
  $to['M'] = $fiscalEnd['1'];
  $to['Y'] = $fiscalEnd['0'];
```

likewise for ```this_N``` cases

2018-02-14 03:37 UTC, eileenmcnaughton commented on CRM/Utils/Date.php
> +          case 'previous_2':
yeah but I feel like it should still cope with the possibility of previous_4

2018-02-14 03:42 UTC, monishdeb commented on CRM/Utils/Date.php
> +          case 'previous_2':
Hmm I see so my multiple cases was if those are predefined and not to allow N number of such terms. So if we need to support previous_4 then I think we should use expression i.e.
```php
case strstr($relativeTerm, 'previous_'):
 ...
```

2018-02-14 04:13 UTC, eileenmcnaughton commented on CRM/Utils/Date.php
> +          case 'previous_2':
yep - or preferably substr or regex I guess,

2018-03-03 11:40 UTC, magnolia61 commented on CRM/Utils/Date.php
> +          case 'previous_2':
Personally I lack the programming skills to make a previous_x variant.
I can see that mechanism would be nice, but might be out of scope of this PR.
Are there any objections to merge it like it is? (just missing additions for fiscal year filters)

2018-04-13 12:51 UTC, monishdeb commented
@magnolia61 sorry for delay I didn't got enough time to review this PR. But before making the remaining fixes, can you please move the upgrade code from ```CRM/Upgrade/Incremental/sql/4.7.31.mysql.tpl``` to ```CRM/Upgrade/Incremental/sql/5.2.alpha1.mysql.tpl``` file ?

2018-04-18 14:31 UTC, MegaphoneJon commented
FWIW the patch that was needed to support relative date filter hooks was merged yesterday.  Let me know if that changes your feelings about this PR @magnolia61!

2018-04-18 15:14 UTC, magnolia61 commented
For me of course I'm looking for a practical solution to be able to work with Fiscal Year filters. I think they lack in core hence this PR. Obviously I support your development of a flexible relative date functionality. But since your PR has finally been merged, I can also see a parallel path where my PR (this PR) is merged and also your flexible variant makes it into an extension. Makes sense?

2018-05-15 11:38 UTC, eileenmcnaughton commented
I took a look at this & concluded I wouldn't feel comfortable adding more handling options to 
CRM_Utils_Date::relativeToAbsolute without a unit test.

I did write a starting point on the unit tests & added 3 of the proposed new options over at 
https://github.com/civicrm/civicrm-core/pull/12137

If you want to test that & review it it can be merged on your testing @magnolia61 

I'm going to close this PR for now because it's stale & I think it would need some tests to progress further. I can help you write tests for the other additions if you do want to go down that path

2018-05-15 11:38 UTC, closed without merging