(misc-core-fixes/issues/2) Make accordion panels accessible
civicrm/civicrm-core pull request #11955
Opened 2018-04-06 12:36 UTC by monishdeb

Overview
----------------------------------------
Currently, in CiviCRM accordions are not accessible which means it doesn't fulfill WAI-ARIA compliance and these are the [guidelines](http://web-accessibility.carnegiemuseums.org/code/accordions/) to make one. By making accessible means other then cursor events we can now rely on control keys to select/open/close an accordion. To do this, I found [jQuery Accessible Accordion System (using ARIA)](https://libraries.io/bower/jquery-accessible-accordion-aria) as the most recommendable JQuery plugin to make an accessible accordion.
    This plugin allows a user to expand an collapse accordion panel by using the keyboard only and not be required to use the mouse. Using ENTER or SPACE user can select and ENTER to toggle an accordion.

In the before/after section below, I will explain what are the advantages of accessible accordion over the current crm-accordion. Also, the screencast provides an overview where all the Contact Edit form accordions are transformed into accessible ones and how we can operate those control keys.

Before
----------------------------------------
Earlier you need to click an accordion to open or close it, not much we can do with control keys:
![test-multiple-before](https://user-images.githubusercontent.com/3735621/38421117-b547477a-39c3-11e8-8082-c4ffcf411bbc.gif)

After
----------------------------------------
![test-multiple-after](https://user-images.githubusercontent.com/3735621/38421559-2b0559f6-39c5-11e8-9c06-7c448ab9719c.gif)

Technical Details
----------------------------------------
Here's what's been done:
1. Added bower library ```"jquery-accessible-accordion-aria": "^2.5"``` to latest stable version i.e. 2.5.1
2. Introduced a jquery function ```jsAccordionToggle(settings)``` that is basically a wrapper to override and initialize the jquery plugin ```accordion(settings)```.
3. As per new accordion format 
```php
<div class="crm-accessible-accordion">
  <div id="panel1" class="crm-accessible-accordion-panel">
    <div class="crm-accessible-accordion-header">
      Header text
    </div>
   ... accordion body ...
  </div> // end of panel 1
  <div id="panel2" class="crm-accessible-accordion-panel"> // start of panel 2
  ...
  </div> // end of panel 2
  ...
</div>
```
4. Css style changes
5. All the accordions on Contact Edit form is changed to accessible ones with the help of new js fn

2018-04-06 12:41 UTC, monishdeb commented
ping @eileenmcnaughton @colemanw @JoeMurray @seamuslee001 @mlutfy 

For now, I have only applied the changes on one form but before proceeding to apply the similar fix to other forms I need your feedback to know if there's any flaw or unintended side effect in this approach.

Thanks!

2018-04-06 12:43 UTC, mattwire commented
@monishdeb Any reason we need to change the class selectors from crm-accordion to crm-accessible-accordion?  If we just applied the accessible accordion to the standard selector there would be far less work in changing core/extension templates to support the accessible accordion.

2018-04-06 12:54 UTC, monishdeb commented
@mattwire thanks for asking this. Actually I am not changing the existing class selectors ```crm-accordion``` but rather added a new class selector  ```crm-accessible-accordion``` which is being used by accessible-plugin to transform the crm accordion to accessible one. So in order to make a accordion accessible, you just need to ensure the desired format (see my 3rd point under Technical Details) 

So right now we are keeping both the selector, but to make a accordion accessible, you need to change the selector to  ```crm-accessible-accordion``` and rest is already handled [here](https://github.com/civicrm/civicrm-core/pull/11955/files#diff-d8719e8d406c65259e59e38cfe10efbeR1570)

2018-04-06 13:31 UTC, mattwire commented
@monishdeb Could you add the "old" accordion format to your 3rd point for comparison?

2018-04-06 13:36 UTC, monishdeb commented
@mattwire  Done :)

2018-04-06 14:46 UTC, mattwire requested changes

2018-04-06 14:46 UTC, mattwire commented on templates/CRM/Contact/Form/Edit/Address.tpl
> +</div><!-- /.crm-accordion-pannel -->
crm-accordion-panel -> crm-accessible-accordion-panel

2018-04-06 14:46 UTC, mattwire commented on templates/CRM/Contact/Form/Edit/TagsAndGroups.tpl
> +</div><!-- /.crm-accordion-panel -->
crm-accordion-panel -> crm-accessible-accordion-panel

2018-04-06 14:46 UTC, mattwire commented on templates/CRM/Contact/Form/Edit/CommunicationPreferences.tpl
> +</div><!-- /.crm-accordion-panel -->
crm-accordion-panel -> crm-accessible-accordion-panel

2018-04-09 13:42 UTC, JoeMurray commented
@colemanw could you provide some general feedback on this general approach so @monishdeb can take advantage of it as he continues with his work on this big initiative. Thanks!

2018-04-12 12:46 UTC, colemanw commented
I agree with @mattwire that the ideal approach would be to not require any markup changes in the tpl and do this all by adjusting the javascript in Common.js.
But just glancing through the code I see some significant differences in how the jQuery plugin and our native accordions work. It might still be possible though. @monishdeb have you already tried something like that?

2018-04-12 16:12 UTC, monishdeb commented
@colemanw yes it is possible, as I recall I can use the existing structure. Just need to pass the class name to the new jquery function, to indicate which one is header and panel (as in [here](https://github.com/civicrm/civicrm-core/pull/11955/files#diff-d8719e8d406c65259e59e38cfe10efbeR1573)). But that also means it will replace the native js handling of civi accordion. The reason, why I felt better to rather add a new class to Civi that makes the accordion accessible on demand. But if it's ok then can I proceed with making the existing civi accordion work with new jquery plugin and remove the unused js code?

2018-04-12 18:55 UTC, JoeMurray commented
Let's get feedback confirming new approach from some appropriate testers. I think it is better to replace existing js like Coleman is suggesting.

2018-06-12 02:05 UTC, eileenmcnaughton commented
@colemanw where are you on this? It seems to be pending more feedback (not sure from who) & is marked as 'wip' but is not active enough to be worth keeping open on that basis.

(note nothing is lost if we close - can still continue discussion on this PR)

2018-06-12 12:52 UTC, JoeMurray commented
Monish please reopen or open a new pr and reference this one when you have reworked as requested by @colemanw .

2018-06-12 12:52 UTC, closed without merging