dev/core/#101: Allow further customization of search form in hooks
civicrm/civicrm-core pull request #12078
Opened 2018-05-03 15:56 UTC by mickadoo

Overview
----------------------------------------

The contact search form uses the template `templates/CRM/Contact/Form/Search/Criteria/Basic.tpl`. In the template there are already some conditionals to hide certain fields, such as

```
{if $form.group}
  <td>
  ...
{/if}
```

However only some fields are covered. For an extension developer who wants to hide more fields here it is difficult without causing warnings or breaking the layout.

To make it easier conditionals should be applied to each form element.

Before
----------------------------------------

Form conditionals were only available for some form elements in the `templates/CRM/Contact/Form/Search/Criteria/Basic.tpl` template

##### What it looked like before:

![before](https://user-images.githubusercontent.com/6374064/39587762-30706eca-4ef2-11e8-8169-dd8e952e52ef.png)

After
----------------------------------------

Form conditionals are available for all form elements in the `templates/CRM/Contact/Form/Search/Criteria/Basic.tpl` template

##### What it looked like after (with no fields changed, should be the same as "Before")

![after_with_all_options](https://user-images.githubusercontent.com/6374064/39587800-4b3d4ea8-4ef2-11e8-9d2f-a9561364adc3.png)

##### What it looked like after with the following fields removed

- email
- job_title
- external_identifier
- privacy_toggle
- email_on_hold
- preferred_communication_method

![after_without_fields](https://user-images.githubusercontent.com/6374064/39587823-5fa77918-4ef2-11e8-949d-685aed382dfb.png)

Notes
----------------------------------------

I reformatted the code a bit, fixing warnings from the IDE. I also changed some existing conditionals to not output anything if the element wasn't set. As it was before they would still show an empty `td` element leading to gaps in the form like:

![conditional_tds](https://user-images.githubusercontent.com/6374064/39587900-8b2b4934-4ef2-11e8-9ac2-29cb23d4ca15.png)

Without these empty `td` elements the gaps are filled:

![conditional_elements](https://user-images.githubusercontent.com/6374064/39587931-965b9f3e-4ef2-11e8-93b4-736c07675015.png)

2018-05-03 18:47 UTC, reneolivo requested changes
### Before
![search-before](https://user-images.githubusercontent.com/1642119/39595941-ee8ab3fc-4ede-11e8-9ea7-7178ffd8c0bc.png)

### After
![search-after](https://user-images.githubusercontent.com/1642119/39596312-f31877f0-4edf-11e8-8772-a9014611d69e.png)
(please refer to comment about this issue)

------

Can you please provide some quick usage example on how you can hide these fields from a plugin? If you can do that I can replicate it locally.

Other than that the changes look good

2018-05-04 13:10 UTC, michaelmcandrew commented
@eileenmcnaughton, i guess you meant @mickadoo

2018-05-08 02:48 UTC, reneolivo commented
Hello @eileenmcnaughton I was investigating the structure of the template and the form controller and even though I agree that looping through each field would be more extensible, I concluded that it would be a bit difficult to implement.

These are the issues I found:
* All the fields are stored in the global `$form` variable and the display of each one of the fields is handled by individual templates:
https://github.com/compucorp/civicrm-core/tree/d9c5047f2c9640316ce8dcadacbd0f4ea005212f/templates/CRM/Contact/Form/Search/Criteria
* As you can see all the sections share their fields in the global `$form` variable and are defined manually. There's no way to tell  the section each field belongs to nor the ones that belong to the basic section.
* Some fields have custom labels defined by the template:
https://github.com/compucorp/civicrm-core/blob/d9c5047f2c9640316ce8dcadacbd0f4ea005212f/templates/CRM/Contact/Form/Search/Criteria/Basic.tpl#L30-L31
* A lot of them have custom logic, more than the ones that don't:
https://github.com/compucorp/civicrm-core/blob/d9c5047f2c9640316ce8dcadacbd0f4ea005212f/templates/CRM/Contact/Form/Search/Criteria/Basic.tpl#L59-L99

Since the solution you propose is not straight forward I suggest implementing this solution for now which works well with the current implementation of the advanced search template.

We could then draw a plan to make the advanced search templates more customizable as a whole.

2018-05-08 03:51 UTC, eileenmcnaughton commented
@reneolivio - my main concern with this 'as is' is that there is a potential that anyone who took advantage of it would later feel burnt if we change it again. 

Regarding "There's no way to tell the section each field belongs to nor the ones that belong to the basic section."

The way we've done it elsewhere (e.g. billing block) is more like 
php 

``
$this->assign('basicSearchFields' => ['sort_name', 'email', 'contact_type'....]);
``

and in the template (not correct code)

``
{foreach value=basicSearchField from=$basicSearchFields} 
  {if file_exists('CRM/Contact/SearchFieldTemplates/$basicSearchField)} 
    {include 'CRM/Contact/SearchFieldTemplates/$basicSearchField'}
  {/else}
    {$form.basicSearchField.label}<br/>
    {$form.basicSearchField.html}
  {/if}
{/foreach}
``

(I don't know if that file exists approach actually works - I was just thinking for a complex field it might be cleaner).

Regarding the labels - in my experience people don't define the labels in the tpl files because they couldn't put in the correct label when adding the field - they just copied another field done that way at some point in time. It shouldn't be too hard to fix those

2018-05-11 00:10 UTC, eileenmcnaughton commented
test this please

2018-05-11 01:09 UTC, eileenmcnaughton commented on CRM/Contact/Form/Search/Criteria.php
> +    $smarty = CRM_Core_Smarty::singleton();
This didn't work for me. What did work was

a) adding a new file called modifier.template_exists.php in packages/Smarty/plugins
b) then clearing smarty caches

I tried using 
https://gitlab.athlonsofia.com/athlon/silla.io/blob/3b669c42e34d72d62f4ac624244d979402c7a98e/resources/smarty_plugins/modifier.template_exists.php

but it didn't work for me so am using 

```
function smarty_modifier_template_exists($template)
{

  $templatePath = __DIR__ . '/../../../templates/' . $template;

  return is_file($templatePath);
}

```

If you want to put up a PR for a new modifer against the packages repo I will merge it

2018-05-11 02:53 UTC, eileenmcnaughton commented
@reneolivo I took a look at this & it seems pretty good. I have a proposal to move from flat field definitions to a fieldSpec - try https://github.com/compucorp/civicrm-core/commit/f4e095a9aa6f9a6ea90b95ff0343a0ee04bff396

- this allows definition of the help file & field in the definition & makes some of the field-specific templates redundant. It is also more extendable later.

Per my comment above - I had to add a modifier to packages to get the smarty include check working - but I'm leaning towards the field tpl being defined in the array (if needed ) ie.

```
      'preferred_language' => [],
      'contact_id' => ['help' => ['id' => 'id-contact-id', 'file' => 'CRM/Contact/Form/Contact']],
      'external_identifier' => ['help' => ['id' => 'id-external-id', 'file' => 'CRM/Contact/Form/Contact']],
      'uf_user' => ['tpl' => 'uf_user.tpl'],
```

It feels like a similar lever of complexity to doing the file_exists in smarty & would be overrideable from php which might be nice.

Other points
1) I'm finding the way email_on_hold is in communication_preferences a bit hacky- but I'm prepared to let that one slide.
2) I'm finding the {if $isTagset} a little confusing - I had it 'cut' with tag_search rather than contact_tags - but I think you may be right. However that would mean we don't need a field template for tag_search

Once you've checked the proposal / comments above we will ping Coleman to check the markup although it seems sane to me

2018-05-16 01:25 UTC, JoeMurray commented
@monish from perspective of wanting fields to define labels in html in way good for supporting a11y, do you see any issues here or have suggestions to make? Ideally these changes when rolled out gradually across the code base would eliminate/greatly reduce the special case handling we are seeing is needed on many fields/forms.

2018-05-17 02:51 UTC, reneolivo commented
Hello @eileenmcnaughton, I cherry-picked your changes, but had to do some fixes too. Here are some pointers:

* The field specs are much, much, better so we should go that way.
* I'm not sure why the previous modifier didn't work for you, does `$smarty->template_exists(...)` work for you?
* I'm not sure how to add a modifier to the package repo and see the changes locally. I found a  `Smarty/plugins/` in core, is it ok to place the modifier there? If not, please guide me on how to to test the modifier when used from the package repo.
* Can we try to use `$smarty->template_exists($templatePath)` instead of:
```php
$templatePath = __DIR__ . '/../../../../templates/' . $template;

return is_file($templatePath);
```
I don't feel `__DIR__` is safe enough.
* I changed the format for the template's help block a bit since it was a really long line.
* There was a mismatched `[]` on the field specs.
* `email_on_hold` was placed inside `preferred_communication_method` because it seems they are part of the same search field, see how they are defined in the same column: https://github.com/compucorp/civicrm-core/blob/master/templates/CRM/Contact/Form/Search/Criteria/Basic.tpl#L151-L156
This is the best solution I could think of, since it doesn't seem one can be displayed without the other. Please let me know if you have a better solution and I can implement it.
* `isTagset` I think you may be right, we need to investigate this a bit more. Do you know how to activate this field so I can determine where to best place it?

2018-05-17 05:15 UTC, eileenmcnaughton commented
@reneolivo did you read this? https://lab.civicrm.org/dev/core/issues/115

When I worked through https://github.com/civicrm/civicrm-core/pull/12128 to achieve a similar outcome I would up preferring to define the tpl rather than use the file_exists

     'weird_looking_field' => [
         'name' => 'weird_looking_field', 
         'template' => CRM/Member/Form/MembershipType/weird_looking_field.tpl',


seems more flexible for overwriting?

2018-05-17 09:56 UTC, reneolivo commented
@eileenmcnaughton I'll have a look at the issue, I didn't get to see it, seems I'll need a bit of time to catch up to the thread. But I rather use convention over configuration: if we manage to make this field extensible it's one less field to configure. 

I'll catch up to issue's thread and also run some tests and let you know.

2018-05-18 17:05 UTC, reneolivo commented
@eileenmcnaughton I have seen the comments on the issue and [your other PR](https://github.com/civicrm/civicrm-core/pull/12128) as well. I approve of the changes, even the `template` field.

I'll wait until your PR gets approved before starting to change this one in case something changes from the spec so we don't duplicate efforts before everything is settled.

Is that ok?

2018-05-20 22:32 UTC, eileenmcnaughton commented
@reneolivo thanks

2018-06-07 00:03 UTC, reneolivo commented
@eileenmcnaughton I have implemented the following changes:

* All the commits have been squashed into one.
* Implemented the field spec pattern as detailed in dev/core#115 and also implemented in https://github.com/civicrm/civicrm-core/pull/12128
* Removed any references to the "template_exists" smarty method. The field spec "template" was favoured instead.

2018-06-07 07:13 UTC, eileenmcnaughton commented
The css seems a bit wrong now
![screenshot 2018-06-07 19 11 52](https://user-images.githubusercontent.com/336308/41083968-da8939d2-6a86-11e8-8a8d-3ad0019a26c0.png)

2018-06-07 07:15 UTC, eileenmcnaughton commented
Also - either as this or as a follow up I think we should extract a form template - i.e we have this one

https://github.com/civicrm/civicrm-core/blob/master/templates/CRM/Core/Form/Field.tpl

but it uses <td> not Div so perhaps 

CRM/Core/Form/FieldDiv.tpl 

too

2018-06-07 07:18 UTC, eileenmcnaughton commented
@reneolivo I started an issue to document the fields format over here https://github.com/civicrm/civicrm-dev-docs/issues/534

2018-06-07 07:32 UTC, eileenmcnaughton commented
Actually css might be OK - might have been cached

2018-06-07 07:41 UTC, eileenmcnaughton commented
OK - I have found one issue but I feel like I looked fairly carefully & we are down to the following

1) If an activity tag type is defined then the 'Include tags used for Activities' doesn't show
2) I don't think we need an override for[ this field](https://github.com/civicrm/civicrm-core/pull/12078/files#diff-be53008955029b86c5982fe6ae27eebb)

Before
![screenshot 2018-06-07 19 11 52](https://user-images.githubusercontent.com/336308/41085292-aaff36cc-6a8a-11e8-9aea-284cda7500be.png)

After
![screenshot 2018-06-07 19 38 00](https://user-images.githubusercontent.com/336308/41085301-b17b0bb6-6a8a-11e8-9d43-3a5abf91f40d.png)

2018-06-08 10:52 UTC, reneolivo commented
@eileenmcnaughton I worked on your feedback. Here are the changes:

![advanced search hr17 9100 1](https://user-images.githubusercontent.com/1642119/41152863-f3226890-6ae2-11e8-9c69-1e1dd092d3ba.png)

* The fields with custom templates were stripped of their wrapper `div.search-field` tag. That tag is now handled at the `Basic.tpl` level.
* Implemented the field description for `phone_numeric` and `uf_user` which made their custom template fields unnecessary.
* `all_tag_types` ("Include tags used for Activities") is displayed if the field is included in the basic search form.

Also, the tag set field is displayed when there is a tag set related to contacts. Since this field was previously displayed by checking if the template has the `$isTagset` variable set to true and it's not a field per se, a `is_custom` was added to the field spec of this field in order to display it. If this property is set to true, it will display the template for the field even if there are no form fields associated to the spec. 

The field is displayed in a new row as opposed to how it was displayed before, in a 4th column, because the CSS grid was already fixed to 3 columns.

It's important to note that CSS grids were chosen over the previous table structure because the former is more flexible when removing a particular field. For example, if one would remove all the cells in a row, the row would still exist, occupying an empty space.

2018-06-08 11:04 UTC, eileenmcnaughton commented
I think we are there on this. I've had a few looks at it & as of yesterday the items you have now addressed were the only outstanding ones. Let's merge -on-pass

2018-06-08 23:00 UTC, merged

2018-06-08 23:00 UTC, eileenmcnaughton commented
bang!

2018-06-11 12:29 UTC, reneolivo commented
First try!
![first-try](https://user-images.githubusercontent.com/1642119/41231599-8290c0f6-6d51-11e8-9958-4f76ee08b629.gif)