CRM-20430 - Permission 'save Report Criteria'.
civicrm/civicrm-core pull request #12107
Opened 2018-05-10 06:32 UTC by eileenmcnaughton

Overview
----------------------------------------
Nuance report permissions, adding a new save report criteria permission

Before
----------------------------------------
Without or with permission 
![screenshot 2018-05-10 18 27 38](https://user-images.githubusercontent.com/336308/39855394-da580ece-547f-11e8-9a62-c9e2ba1bef73.png)

After
----------------------------------------
Without permission 

![screenshot 2018-05-10 18 26 52](https://user-images.githubusercontent.com/336308/39855363-c205f930-547f-11e8-94e9-a9de4a650fdf.png)

With permission
![screenshot 2018-05-10 18 29 04](https://user-images.githubusercontent.com/336308/39855443-0ccb24a4-5480-11e8-9500-da27e6135239.png)

Technical Details
----------------------------------------
I am torn between renaming the perm to 'edit report_templates' for consistency with other entities or sticking with 'save Report Criteria' to be more consistent with other report perms - per original submitter

Comments
----------------------------------------
This is a recut of https://github.com/civicrm/civicrm-core/pull/10164 with the things that were blocking it tweaked. It does makes sense & has made sense to others - however, I won't keep this open if it is not merged by the time the 5.3 rc is recut that is it's 'last chance'

2018-05-11 12:23 UTC, tschuettler requested changes
(*CiviCRM Review Template WORD-1.1*)

<!-- In each category, change the word "Undecided" to "Pass" or "Issue". Add explanatory comments if prompted or desired. -->

* ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain)) __Pass__
* ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test)) __Pass__
* ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code)) __Pass__
* ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc)) __Pass__
* ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint)) __Pass__
* ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run)) __Pass__: Can save or copy reports with the new permission. Don't have the option to do so without it.
* ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user)) __Pass__: A pre-upgrade warning to review the permissions exists.
* ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech)) __Issue__: see below
* ([`rg-upgrades`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech)) __Issue__: Pre-upgrade message is displayed twice when upgrading from <4.7.32.
* ([`rg-perm`](https://docs.civicrm.org/dev/en/latest/standards/review/#rg-perm)) __Undecided__: Should this permission be added to the civicrm_webtest_user role in civibuild or [civicrm_webtest.install](https://github.com/civicrm/civicrm-core/blob/master/tools/drupal/modules/civicrm_webtest/civicrm_webtest.install) so that users can test saving reports on dmaster demo?

2018-05-11 12:55 UTC, eileenmcnaughton commented
@tschuettler thanks for the review - I've fixed the 4.7.32 double up. Good point about demo site permissions  - I feel like this is something that has been off our radar when adding perms - @totten how do we best handle / audit this

(current test failure is not related I believe -looks like server resources)

2018-05-11 13:31 UTC, tschuettler commented
Thanks @eileenmcnaughton!
There was https://github.com/civicrm/civicrm-core/pull/9785 that did add permissions. It feels reasonable to add it directly.

(Seems like the installation did not even finish this time since the mysql server was down)

2018-05-11 20:51 UTC, eileenmcnaughton commented
Hmm - are those permissions what is not used in buildkit or are they legacy - I think this might be where I need to add them - https://github.com/civicrm/civicrm-buildkit/search?utf8=%E2%9C%93&q=access_civimail&type=

2018-05-11 20:53 UTC, eileenmcnaughton commented
test this please

2018-05-15 03:07 UTC, eileenmcnaughton commented
test this please

2018-05-15 07:58 UTC, eileenmcnaughton commented
@totten can you comment on where we need to add permissions for the buildkit / demo environment?

2018-06-08 23:29 UTC, totten commented
@eileenmcnaughton -- @tschuettler's reference to `civicrm_webtest` should be correct. In the build scripts, the first step for setting permissions to enable `civicrm_webtest`:

* For drupal-clean (used by Jenkins CI for automated testing): https://github.com/civicrm/civicrm-buildkit/blob/20b7bd80d38c477ec2179b5e66861bb8c1297bb7/app/config/drupal-clean/install.sh#L55-L64

* For drupal-demo (used for demo sites): https://github.com/civicrm/civicrm-buildkit/blob/20b7bd80d38c477ec2179b5e66861bb8c1297bb7/app/config/drupal-demo/install.sh#L78-L81

Note: the `drupal-demo` site goes a bit further and assigns *additional* permissions.

Phrased another way:

* If you want to apply the permission broadly (on all test/demo systems), update `civicrm_webtest.install`
* If you want to apply the permission on a narrower subset (e.g. only test sites; or only demo sites), then update the `app/config/<foo>/install.sh` in `civicrm-buildkit`.

2018-06-08 23:33 UTC, eileenmcnaughton commented
hmm - that's intuitive - update a drupal module for generic permissions. I don't even want to ask about WP & Joomla! :-) Doing it now & will merge this once done as I feel this satisfies the review

2018-06-09 01:32 UTC, eileenmcnaughton commented
unrelated fail - merging

2018-06-09 01:32 UTC, merged