Towards dev/financial/#16 Paypal unreliable getting payment processor type
civicrm/civicrm-core pull request #12174
Opened 2018-05-21 04:23 UTC by eileenmcnaughton

Overview
----------------------------------------
Second reviewer's commit of #12007 - code standardisation in paypal class to prevent e-notices & missing details in messages

Before
----------------------------------------
PHP notice on some payment submissions (eg. via webform_civicrm) and use of "non-standard" param.

After
----------------------------------------
No PHP notice and uses standard parameter so it works with all payment submissions that use standard methods to populate the payment processor array ($this->_paymentProcessor).

Related: #12091

Technical Details
----------------------------------------

Comments
----------------------------------------
@mattwire if you can confirm this still seems good to you I will merge it. I basically went through your commit & re-did it - removing the problematic line in isSupported & fixing this incorrect change
https://github.com/civicrm/civicrm-core/pull/12091/files#diff-96a0ea19e8ac102ef100c35b3b3d1c31R506

I feel OK about this now (as a reviewer's commit)

2018-05-24 00:34 UTC, eileenmcnaughton commented
@mattwire this is also waiting for re-review from you

2018-05-27 15:39 UTC, mattwire requested changes
@eileenmcnaughton Ok, reviewed and tested this.  It's effectively no functional change as we're just replacing string checks with const checks which should be more reliable.  If you could just add the `@deprecated` tag to _processorName then it's ok to merge.

2018-05-27 15:39 UTC, mattwire commented on CRM/Core/Payment.php
> +   * (Deprecated parameter but used in some messages).
`* @deprecated (Deprecated parameter but used in some messages).`

2018-05-27 15:39 UTC, mattwire commented on CRM/Core/Payment/PayPalImpl.php
> +    if ($this->isPayPalType($this::PAYPAL_PRO)) {
Yes

2018-05-27 15:39 UTC, mattwire commented on CRM/Core/Payment/PayPalImpl.php
> +    if ($this->isPayPalType($this::PAYPAL_EXPRESS) || $this->isPayPalType($this::PAYPAL_PRO)) {
Yes

2018-05-27 15:39 UTC, mattwire commented on CRM/Core/Payment/PayPalImpl.php
> +      if ($this->isPayPalType($this::PAYPAL_EXPRESS)) {
Yes

2018-05-27 15:39 UTC, mattwire commented on CRM/Core/Payment/PayPalImpl.php
> +      if ($this->isPayPalType($this::PAYPAL_PRO)) {
Yes

2018-05-27 15:39 UTC, mattwire commented on CRM/Core/Payment/PayPalImpl.php
> +    if ($this->isPayPalType($this::PAYPAL_PRO) && !$this->isPaypalExpress($values)) {
Yes

2018-05-27 15:39 UTC, mattwire commented on CRM/Core/Payment/PayPalImpl.php
> +    if ($this->isPayPalType($this::PAYPAL_EXPRESS) || ($this->isPayPalType($this::PAYPAL_PRO) && !empty($params['token']))) {
Yes

2018-05-27 15:39 UTC, mattwire commented on CRM/Core/Payment/PayPalImpl.php
> +    if (!$this->isPayPalType($this::PAYPAL_STANDARD)) {
Yes

2018-05-27 15:39 UTC, mattwire commented on CRM/Core/Payment/PayPalImpl.php
> +    if ($this->isPayPalType($this::PAYPAL_STANDARD)) {
Yes

2018-05-27 15:39 UTC, mattwire commented on CRM/Core/Payment/PayPalImpl.php
> +    if (!$this->isPayPalType($this::PAYPAL_PRO)) {
Yes

2018-05-27 15:39 UTC, mattwire commented on CRM/Core/Payment/PayPalImpl.php
> +    if ($this->isPayPalType($this::PAYPAL_EXPRESS)) {
Yes

2018-05-27 15:39 UTC, mattwire commented on CRM/Core/Payment/PayPalImpl.php
> +    if ($this->isPayPalType($this::PAYPAL_PRO)) {
Yes

2018-05-27 15:39 UTC, mattwire commented on CRM/Core/Payment/PayPalImpl.php
> +    if ($this->isPayPalType($this::PAYPAL_PRO)) {
Yes

2018-05-27 15:39 UTC, mattwire commented on CRM/Core/Payment/PayPalImpl.php
> +    if ($this->isPayPalType($this::PAYPAL_PRO)) {
Yes

2018-05-27 15:39 UTC, mattwire commented on CRM/Core/Payment/PayPalImpl.php
> +    if ($this->isPayPalType($this::PAYPAL_PRO)) {
Yes

2018-05-27 15:39 UTC, mattwire commented on CRM/Core/Payment/PayPalImpl.php
> +    if ($this->isPayPalType($this::PAYPAL_EXPRESS)) {
Yes

2018-05-27 21:46 UTC, merged