Allow vendor directory outside of docroot
civicrm/civicrm-core pull request #12198
Opened 2018-05-24 16:55 UTC by dsnopek

It's considered best practice with composer-based webapps to keep the vendor directory outside the webroot. This change looks for it in the directory above.

2018-06-04 07:47 UTC, monishdeb commented on CRM/Utils/System/Drupal8.php
> +    foreach ($autoload_possible_paths as $autoload_path) {
@dsnopek can you change it to
```patch
- $autoload_possible_paths = array($root, $root . "/..");
- foreach ($autoload_possible_paths as $autoload_path) {
+ foreach ([$root, $root . "/.."] as $autoload_path) {
```
as $autoload_possible_paths is no longer used anywhere.

2018-06-04 07:52 UTC, monishdeb requested changes
Tested the patch and it correctly detects the autoloader file outside the webroot. However from code pov it needs a minor change as mentioned in the patch.

2018-06-04 07:52 UTC, monishdeb commented on CRM/Utils/System/Drupal8.php
> +    $autoload_possible_paths = array($root, $root . "/..");
@dsnopek can you change it to
```patch
- $autoload_possible_paths = array($root, $root . "/..");
- foreach ($autoload_possible_paths as $autoload_path) {
+ foreach ([$root, $root . "/.."] as $autoload_path) {
```
as $autoload_possible_paths is no longer used anywhere.

2018-07-18 13:54 UTC, eileenmcnaughton commented
closing for #12499

2018-07-18 13:54 UTC, closed without merging