dev/cloud-native/issues#18: Soften messages for read-only extensionsDir
civicrm/civicrm-core pull request #12623
Opened 2018-08-04 20:07 UTC by tiotsop01

Overview
----------------------------------------
Improve messaging when someone has a different policy for managing extensionsDir.  Most of the messaging update has already been done. There is only one message ("Read-Only Extensions"). It still encourages web-writable policy, but it lowers the severity and presents it a choice ("if you want X, do Y").

Before
----------------------------------------
The message that is displayed is a `warning` when the directory is "Read-Only" which implies something is wrong.

After
----------------------------------------
The message that is displayed is a `notice` when the directory is "Read-Only". `notice` says it's merely out of the ordinary

Comments
----------------------------------------
This a continuation of this PR [#11895](https://github.com/civicrm/civicrm-core/pull/11895).

2018-08-04 20:07 UTC, civicrm-builder commented
Can one of the admins verify this patch?

2018-08-05 07:01 UTC, eileenmcnaughton commented
test this please

2018-09-17 03:18 UTC, eileenmcnaughton commented
@tiotsop01 I'm fine with downgrading the error level - I'm just not sure what the Settings file means in the below context

'Writing to Settings file has been disabled by admin'

Perhaps you mean 'Please check with your system admin if file permissions have been restricted deliberately'?

@agh1 this was your wording in the first place

2018-09-17 14:33 UTC, agh1 requested changes
I think it's fine to downgrade a non-writable extensions directory to `notice`.  When we picked `warning`, it's because it seemed to fit the [PSR-3 standard of a warning](https://github.com/php-fig/log/blob/master/Psr/Log/LoggerInterface.php#L69): an exceptional occurrence that's not an error--an undesirable thing that is not necessarily wrong.  However, if we see the situation of in-app extension downloads as a nice bonus rather than a core feature, I can see it matching the `notice` criteria.

On the other hand, those other directories really need to be writable.  Also, the "writing to Settings file" text doesn't really describe what's going on.  If you want to elaborate in the message, it might be better to have different messages keyed to each file that describe the problem.  However, I think the labels are enough, and the main thing for the site admin is that they need to go make them writable regardless.

2018-09-17 14:33 UTC, agh1 commented on CRM/Utils/Check/Component/Env.php
> +        ts('The %1 is not writable. Writing to Settings file has been disabled by admin. Please check your file permissions.', array(
I agree with @eileenmcnaughton that this text "writing to Settings file has been disabled by admin" is confusing.  This warning can appear in several situations, but I don't think any of them involve writing to a settings file.

2018-09-17 14:33 UTC, agh1 commented on CRM/Utils/Check/Component/Env.php
> +        \Psr\Log\LogLevel::NOTICE,
This should remain an `error`: it's a real problem if CiviCRM can't upload import files, images, or custom files.  In nearly all cases, a site that can't write to these folders will appear "broken" to someone trying to do regular tasks like running imports or uploading a file to a custom field.

2018-09-17 14:37 UTC, agh1 commented
Just adding a link back to [dev/cloud-native#18](https://lab.civicrm.org/dev/cloud-native/issues/18) for convenience.

2018-11-15 12:24 UTC, closed without merging