Fix duplicate merge to not disregard zero values.
civicrm/civicrm-core pull request #12669
Opened 2018-08-15 21:59 UTC by eileenmcnaughton

Overview
----------------------------------------
Fix merge process to treat 0 as different to NULL

Before
----------------------------------------
A contact who has selected 0 for a checkbox field is merged to a contact who has a NULL value. The 0 value is not transferred over.

After
----------------------------------------
A contact who has selected 0 for a checkbox field is merged to a contact who has a NULL value. The 0 value is transferred over.

Technical Details
----------------------------------------
In a checkbox situation the difference between
0 and null is significant (I chose not to opt in vs
I was never presented with a choice).

I would note that further digging is required to see how a conflict is handled
- ie. if one contact has 0 & the other has 1 is this blocked as a conflict and I may do this as a follow up

ping @JKingsnorth

2018-08-15 22:00 UTC, eileenmcnaughton commented
@ejegg @mepps

2018-08-16 20:23 UTC, ejegg requested changes
Looks like a good set of tests! Let's also ignore empty arrays (when I tried to apply similar logic to the non-custom field bit it found a lot of those) and do strict comparison in the in_array test.

2018-08-16 23:02 UTC, seamuslee001 commented
@eileenmcnaughton the test failures i think might be related https://test.civicrm.org/job/CiviCRM-Core-PR/22120/

2018-08-17 00:34 UTC, eileenmcnaughton commented on CRM/Dedupe/Merger.php
> +      if (!in_array($key1, $valuesToIgnore) || !in_array($key2, $valuesToIgnore)) {
@ejegg good thinking - done. Also port in gerrit

2018-08-28 01:53 UTC, eileenmcnaughton commented
@JKingsnorth @deepak-srivastava any takers for review?

2018-08-28 21:12 UTC, JKingsnorth commented
@eileenmcnaughton I'll review this tomorrow [=

2018-08-28 21:14 UTC, eileenmcnaughton commented
thanks @JKingsnorth

2018-08-29 20:42 UTC, JKingsnorth commented
Sorry, something came up, first on my list tomorrow.

2018-08-30 10:12 UTC, JKingsnorth commented
I'm currently unable to recreate the original issue, by doing:

- I created an optional checkbox with the values Zero - 0 and One - 1
- I created two contacts, one with 0 and one with 1
- I batch merged them
- Conflict detected on batch merge (before patch was applied)

So I've opened a PR with just the tests to investigate further: https://github.com/civicrm/civicrm-core/pull/12750

2018-08-31 08:59 UTC, JKingsnorth commented
@eileenmcnaughton - weird, the tests you wrote passed without the patch!

So presumably we can keep the code as-is (unless you can dig out the steps to recreate the issue you were experiencing) and just add the tests?

2018-10-20 22:34 UTC, mattwire commented
@eileenmcnaughton What's the status with this one?

2018-12-19 19:36 UTC, monishdeb commented
@eileenmcnaughton @JKingsnorth @mattwire I have moved and modified the UTs in a separate PR to capture the two use-cases. This is the https://github.com/civicrm/civicrm-core/pull/13323 which is expected to fail without this patch. Please have a look

2018-12-20 04:40 UTC, monishdeb commented
I am merging this PR as it fixes the issue. As per the UT concern, I made the desired change in UT (PR #13323) to capture this use-case. After merge I will rebase my PR for merge-on-pass, to show this fix worked for ```''``` and  ```NULL```

2018-12-20 04:40 UTC, merged

2018-12-20 04:41 UTC, eileenmcnaughton commented
Thanks @monishdeb