Mem2
civicrm/civicrm-core pull request #12695
Opened 2018-08-20 05:18 UTC by eileenmcnaughton

Overview
----------------------------------------
_A brief description of the pull request. Try to keep it non-technical._

Before
----------------------------------------
_The current status. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

After
----------------------------------------
_What has been changed. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

Technical Details
----------------------------------------
_If the PR introduces noteworthy technical changes, please describe them here. Provide code snippets if necessary_

Comments
----------------------------------------
_Anything else you would like the reviewer to note_

2018-08-28 11:14 UTC, mattwire commented
@eileenmcnaughton Test failures are related `Missing argument 1 for CRM_Member_Form_Membership::emailMembershipReceipt()`

2018-08-28 22:12 UTC, eileenmcnaughton commented
@mattwire fixed

2018-08-31 00:57 UTC, eileenmcnaughton commented
test this please

2018-08-31 00:58 UTC, eileenmcnaughton commented on CRM/Member/Form/Membership.php
> -    // retrieve custom data
moved to getCustomValuesForReceipt which is called from the form function (but not the function shared with the BatchEntry task)

2018-09-08 09:46 UTC, mattwire commented on CRM/Member/Form/Membership.php
> +    // @tod figure out how much of the stuff below is genuinely shared with the batch form & a logical shared place.
@eileenmcnaughton Typo @tod => @todo :-)

2018-09-08 09:50 UTC, mattwire commented on CRM/Member/Form/Membership.php
> +    return [$membership, $mailSend];
Are these return values ever used?

2018-09-08 09:50 UTC, mattwire commented on CRM/Member/Form/Membership.php
> +      $mailSend = $this->emailMembershipReceipt($formValues, $membership);
I don't think $mailSend is ever used?  Also, emailMembershipReceipt is returning an array and $mailSend is the second element...

2018-09-08 09:51 UTC, mattwire requested changes
@eileenmcnaughton Not sure about return parameters from emailMembershipReceipt()

2018-10-10 13:46 UTC, mattwire commented on CRM/Member/Form/Membership.php
> +      $mailSend = $this->emailMembershipReceipt($formValues, $membership);
ok

2018-10-10 14:01 UTC, mattwire commented
Tested this and reviewed code.  Still works as before but code is cleaner. Merge on pass

2018-10-10 21:33 UTC, seamuslee001 commented
Test fails unrelated merging as per the tag

2018-10-10 21:33 UTC, merged