WIP dev/core#362 fix contact reference fields on On Behalf Profiles search functionality
civicrm/civicrm-core pull request #12790
Opened 2018-09-06 18:16 UTC by alifrumin

Overview
----------------------------------------
This pr addresses a bug where for contact reference fields in on behalf profiles, the search and select functionality was breaking because of some confusion around naming (onbehalf_custom_12 vs custom_12). More notes: https://lab.civicrm.org/dev/core/issues/362

Before
----------------------------------------
When a Contact Reference field is added to an On Behalf of profile on a Donation/Membership page it is displayed but the search and select function never populates on the page. No error is generated.

After
----------------------------------------
Contact Reference fields in On behalf profiles work as expected.

2018-09-07 08:18 UTC, eileenmcnaughton commented
@lcdservices maybe you could review this?

2018-09-07 15:18 UTC, alifrumin commented
Changing this to a WIP because this fix breaks contact reference fields on backend forms

2018-09-09 23:05 UTC, eileenmcnaughton commented on templates/CRM/Custom/Form/ContactReference.tpl
> +    var $field = $("{/literal}#{if $prefix}{$prefix}_{/if}{$element_name|replace:']':''|replace:'[':'_'}{literal}");
I think we are better to half any _ in the prefix - otherwise it's too easy to have in some places & not others

2018-09-13 15:31 UTC, alifrumin commented
test this please

2018-09-13 16:35 UTC, alifrumin commented
It looks like the failing tests are unrelated:  api_v3_JobProcessMailingTest::testConcurrency.testConcurrency with data set #0

2018-09-14 00:29 UTC, eileenmcnaughton commented
test fails are unrelated @alifrumin was there someone else with an interest in this we can ask to review?

2018-09-14 15:29 UTC, alifrumin commented
hmmm, not that I can think of, I can bug someone about it at the governance sprint in a couple weeks.

2018-09-25 20:56 UTC, colemanw commented
@alifrumin time to bug someone :)

2018-09-27 16:56 UTC, MegaphoneJon requested changes
I reviewed this today at the sprint.  In consultation with @alifrumin we decided that a different approach focusing on changes in `templates/CRM/Contribute/Form/Contribution/OnBehalfOf.tpl` could achieve the same effect with fewer potential side effects.

2018-09-27 19:46 UTC, MegaphoneJon commented
I had concerns about `r-tech` and `r-code` - first, that the id of elements on other forms would be impacted, and second that the code was unclear in its purpose.  @alifrumin demonstrated the robustness of this approach and satisfied me that my first concerns were unfounded, and added comments to satisfy my `r-code` concerns.  I successfully tested this and recommend a merge-on-pass.

2018-09-27 19:46 UTC, MegaphoneJon approved these changes

2018-09-28 01:16 UTC, eileenmcnaughton commented
merging based on @MegaphoneJon review

2018-09-28 01:16 UTC, merged

2018-09-28 01:42 UTC, alifrumin commented
Thank you @MegaphoneJon and @eileenmcnaughton

2018-12-31 01:46 UTC, eileenmcnaughton commented
@alifrumin @MegaphoneJon I'm pretty sure this fix has caused https://lab.civicrm.org/dev/core/issues/619 :-( 
Also - oddly the thing it was supposed to fix is currently broken too...

2018-12-31 16:44 UTC, alifrumin commented
hmm, I will brainstorm on this