Price Set Custom search: add Participant status as filter
civicrm/civicrm-core pull request #13357
Opened 2018-12-27 07:54 UTC by sunilpawar

Overview
----------------------------------------
Add Participant status as filter to custom search

Before
----------------------------------------
Status field was absent in filter criteria

After
----------------------------------------
Status Field is present (mult-select)

2019-02-18 23:11 UTC, eileenmcnaughton commented
@colemanw where are you at on this - do we actually accept new features to the build in custom searches? Ideally instead it would be removed from core & go in an extension where people can add & maintain - where are you at with this?

I would note there is no test & while it perhaps shouldn't be reviewed without one - if the review is going to be to say 'do it in an extension' we should do that before asking for a test....

2019-02-23 20:57 UTC, colemanw commented on CRM/Contact/Form/Search/Custom/PriceSet.php
> +INNER JOIN civicrm_participant_status_type participant_status ON (tempTable.status_id = participant_status.id)
Doing this as a join may hurt performance. In other searches we look up the options with PHP when rendering results.

2019-02-23 20:58 UTC, colemanw commented on CRM/Contact/Form/Search/Custom/PriceSet.php
> +        'multiple' => 'multiple',
Typically we say `'multiple' => TRUE`

2019-02-23 20:59 UTC, colemanw commented
I think the custom search ought to go in an extension but for now it's in core so this PR is appropriate. Merging this PR doesn't stop us from moving the search to an extension at some point.

2019-02-23 20:59 UTC, colemanw requested changes
I'd be inclined to merge this if it can be implemented without an extra join.

2019-02-24 00:23 UTC, eileenmcnaughton commented
@colemanw I think we should get a test too - if something breaks we still have to deal with the fallout so I don't think we should drop the test requirement in the under-maintained & flakey sections of code - esp not for an additional feature rather than a bug fix

2019-05-20 02:33 UTC, eileenmcnaughton commented
Closing to track through gitlab as this is stale, without a test & review is not addressed - treating as inactive for now

2019-05-20 02:33 UTC, closed without merging