CRM/Logging - Fix various bugs in schema parsing
civicrm/civicrm-core pull request #13441
Opened 2019-01-13 18:40 UTC by patf

Overview
----------------------------------------
`CRM_Logging_Schema` contains a number of helper methods for parsing table schemas. The results are then used to create or alter log tables.

Before
----------------------------------------
Some of these methods contain bugs that produce incorrect or incomplete results:

- `CRM_Logging_Schema::getIndexesForTable` only queries for constraints, not returning any indexes.
- `CRM_Logging_Schema::getIndexesForTable` returns an array in the form `[0 => ['constraint_name' => 'foo']]`, meaning lookups via `in_array` won't work.
- `CRM_Logging_Schema::columnSpecsOf` contains an off-by-one error and a wrongly used substr parameter causing column lengths to include surrounding parenthesis. This would result in a `varchar(42)`column returning a length of `(42)`.

After
----------------------------------------

- `CRM_Logging_Schema::getIndexesForTable` returns constraints as well as indexes.
- `CRM_Logging_Schema::getIndexesForTable` returns an array in the form of `['index1', 'index2', ...]`
- `CRM_Logging_Schema::columnSpecsOf` returns column lengths without surrounding parenthesis.

2019-01-13 18:40 UTC, civicrm-builder commented
Can one of the admins verify this patch?

2019-01-13 19:55 UTC, seamuslee001 commented
Jenkins add to whitelist

2019-01-24 19:23 UTC, colemanw commented
That would be great @aydun - thanks.

2019-01-25 15:23 UTC, aydun requested changes
Generally looks good, and does what it says.  Good to see a test.

`getIndexesForTable` is only called from `updateLogTableSchema` so looks fairly low impact.  Would be good to fix the enum length thing but I don't think it actually causes any failures.

2019-01-25 15:23 UTC, aydun commented on tests/phpunit/CRM/Logging/SchemaTest.php
> +      PRIMARY KEY (`test_id`)
Add an `enum` column

2019-01-25 15:23 UTC, aydun commented on tests/phpunit/CRM/Logging/SchemaTest.php
> +  }
Test length on `enum`

2019-01-25 19:00 UTC, patf commented
Thanks @aydun! I added some code that should handle enums as well as tests for length/enum changes getting pushed through to log tables.

2019-02-23 11:50 UTC, mattwire commented
test this please

2019-02-24 05:20 UTC, eileenmcnaughton commented
I'm going to merge this - I feel like feedback has been responded to & test coverage is great. I would also note this code is accessed only when updating logging tables & has pretty reasonable coverage so that gives me some confidence

2019-02-24 05:20 UTC, merged