dev/core#913 - update autogenerated .htaccess for apache 2.4
civicrm/civicrm-core pull request #14158
Opened 2019-04-30 01:16 UTC by demeritcowboy

Overview
----------------------------------------
See https://lab.civicrm.org/dev/core/issues/913

Before
----------------------------------------
The current autogenerated .htaccess is for apache 2.2. It happens to work on apache 2.4 because it gives an internal error, but that's obviously not what was intended. It may also happen to work on apache 2.4 if mod_access_compat happens to be installed.

After
----------------------------------------
Works on apache 2.4 with no log errors. Falls back to current behavior if it can't tell if it's apache 2.4 or higher.

2019-05-01 00:28 UTC, pfigel requested changes
You can use something like this to have a single `.htaccess` that is compatible with both versions of apache:
```
# Apache 2.2
<IfModule !authz_core_module>
  Order Deny,Allow
  Deny from all
</IfModule>

# Apache 2.4+
<IfModule authz_core_module>
  <RequireAll>
    Require all denied
  </RequireAll>
</IfModule>
```

This has the advantage of continuing to work if installs move back and forth between apache versions (or if version detection fails).

(Based on [an example in .htaccess made easy](https://htaccessbook.com/access-control-apache-2-4/#conditional).)

2019-05-01 01:34 UTC, demeritcowboy commented
Thanks! I'll take a look. Makes sense. The `Order` is backwards but it's because in that example they are doing something slightly different. Similarly the RequireAll isn't needed. Anyway I have a 2.2 and 2.4 so I'll test it out.

2019-05-01 02:08 UTC, demeritcowboy commented
Oops. Somehow that closed the PR.

2019-05-01 23:34 UTC, pfigel approved these changes
Looks great now, thanks @demeritcowboy!

(*CiviCRM Review Template WORD-1.2*)

* General standards
    * ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain)) __PASS__
    * ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user)) __PASS__: Fixes a bug with little user impact.
    * ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc)) __PASS__
    * ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run)) __PASS__: Config blocked access when tested against apache 2.2 and 2.4.
* Developer standards
    * ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech)) __PASS__: Fix improves compatibility.
    * ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code)) __PASS__
    * ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint)) __PASS__
    * ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test)) __PASS__

2019-05-01 23:58 UTC, demeritcowboy commented
Thanks for reviewing @pfigel

2019-05-25 23:41 UTC, eileenmcnaughton commented
reviewing based on @pfigel review

2019-05-25 23:41 UTC, merged

2019-06-04 17:43 UTC, edvanleeuwen commented
Duplicate of https://issues.civicrm.org/jira/browse/CRM-21571

2019-06-04 18:00 UTC, demeritcowboy commented
@edvanleeuwen Ahh I never saw that. I see you had some technical trouble getting a pull request posted back then - it is pretty tricky. You can see farther up here I accidentally closed this one in the middle somehow and I'm still not sure how I did that. I don't know if you asked in chat.civicrm.org back then but in future you can also ask there which is sometimes helpful for those technical hurdles.