dev/core#723 Fix fatal error when trying to merge contacts with a cus…
civicrm/civicrm-core pull request #14325
Opened 2019-05-24 22:34 UTC by eileenmcnaughton

…tom file field

Technical comments here https://lab.civicrm.org/dev/core/issues/723#note_16231

Overview
----------------------------------------
_A brief description of the pull request. Try to keep it non-technical._

Before
----------------------------------------
_The current status. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

After
----------------------------------------
_What has been changed. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

Technical Details
----------------------------------------
_If the PR introduces noteworthy technical changes, please describe them here. Provide code snippets if necessary_

Comments
----------------------------------------
_Anything else you would like the reviewer to note_

2019-05-28 20:44 UTC, eileenmcnaughton commented
@lcdservices are you able to test this?

2019-05-29 16:00 UTC, twomice commented
Reviewing this now.

2019-05-29 17:21 UTC, twomice requested changes
(*CiviCRM Review Template WORD-1.2*)

<!-- In each category, change the word "Undecided" to "Pass" or "Issue". Add explanatory comments if prompted or desired. -->

* General standards
    * ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain)) __Issue__: minor typos/grammar/clarification in code comments; see my review comments.
    * ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user)) __Pass__: <!-- Describe -->
    * ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc)) __Pass__
    * ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run)) __Pass__: 
        * Verified the issue exists in master, reproduced with steps in [dev/core#723](https://lab.civicrm.org/dev/core/issues/723): observed fatal error as described.
        * After applying PR, repeated same steps, and observed:
            * no fatal error
            * file was correctly moved to surviving contact in merge.
* Developer standards
    * ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech)) __Issue__:
        * The PR "Technical Details" mentions that "the profile.create hook would be bypassed"; does this refer to hook_civicrm_post() and hook_civicrm_pre() ?  I'm not aware of the likely impact of this change, and it's hard to cr; could be worth a PSA to extension developers.
    * ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code)) __Pass__
    * ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint)) __Pass__: PR includes changes to an existing test, which is passing. 
    * ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test)) __Pass__

2019-05-29 19:10 UTC, eileenmcnaughton commented
@twomice thanks - I've update the comments you pointed to. Regarding switching to not using profile create - this PR doesn't actually make that change but yes perhaps if once soon does we should send a PSA

2019-05-30 12:59 UTC, twomice commented
@eileenmcnaughton Thanks for the work on this -- I am very happy (and surely it's not just me) to see this getting resolved.  Thanks for explaining about the hook; I just assumed I was missing something there.

So I'll approve this as officially as I can. Anything else I can do to help get this merged?

2019-05-30 21:31 UTC, eileenmcnaughton commented
Thanks @twomice - I'll merge it - I'm gonna take this a bit further so hopefully you will review the follow ups too

2019-05-30 21:31 UTC, merged

2019-05-31 14:35 UTC, twomice commented
Yes, hopefully.