Allow updating ENGINE_CONFIG for System.updatelogtables
civicrm/civicrm-core pull request #14348
Opened 2019-05-26 19:45 UTC by mattwire

Overview
----------------------------------------
Allow you to update the ENGINE_CONFIG via System.updatelogtables if you are not changing the actual storage engine.
I needed to go from InnoDB `ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=4` to InnoDB `ROW_FORMAT=DYNAMIC` and you can't do it via this API function without changing the engine too.

Also return the number of tables we updated as a result instead of "1" in the API call.

Before
----------------------------------------
Cannot modify SQL engine config for log tables.

After
----------------------------------------
Can modify SQL engine config for log tables.

Technical Details
----------------------------------------
Just follows the same principal as existing code.  Enabled via parameter so no change by default.

Comments
----------------------------------------
@seamuslee001 @mfb @pfigel

2019-05-26 21:02 UTC, seamuslee001 commented
Test failure relates @mattwire https://test.civicrm.org/job/CiviCRM-Core-PR/26463/testReport/junit/(root)/CRM_Logging_SchemaTest/testColumnInfo/

2019-05-26 21:25 UTC, pfigel commented
I'm wondering if we really need a new API parameter or if just checking for a difference is good enough. Seems like it would be a sane default behaviour, unless we have good reason to be more conservative. Thoughts?

2019-06-01 18:51 UTC, mattwire commented
@pfigel I think it makes sense to be conservative (and add the param) when we first add it, just in case it should cause any problems.

2019-06-02 21:17 UTC, pfigel requested changes
@mattwire LGTM!

* General standards
    * ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain)) __PASS__
    * ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user)) __PASS__: No change in default behaviour - hidden behind new parameter with appropriate docs.
    * ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc)) __PASS__
    * ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run)) __PASS__: Confirmed engine config is changed with `updateChangedEngineConfig=1` and not changed otherwise.
* Developer standards
    * ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech)) __PASS__: Minor (useful) change in return value, unlikely to have ecosystem impact.
    * ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code)) __PASS__
    * ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint)) __PASS__
    * ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test)) __PASS__

2019-06-02 21:18 UTC, pfigel approved these changes
Whoops, noticed the test failure was already resolved, so definitely LGTM now.

2019-06-03 09:55 UTC, monishdeb commented
@mattwire @pfigel is there anything remaining or I can merged it given that @pfigel has already reviewed and approved it?

2019-06-03 10:22 UTC, mattwire commented
@monishdeb I'm happy!

2019-06-03 10:44 UTC, monishdeb commented
Great .. Let us wait for @pfigel reply and I'll then merge this PR after his approval.

2019-06-03 13:26 UTC, pfigel commented
@monishdeb I'm happy with this!

2019-06-03 13:28 UTC, merged

2019-06-03 13:28 UTC, monishdeb commented
Merged. Thanks guys for all your effort.