Add api for Dedupe.getduplicates
civicrm/civicrm-core pull request #14411
Opened 2019-06-03 04:22 UTC by eileenmcnaughton

Overview
----------------------------------------
_A brief description of the pull request. Try to keep it non-technical._

Before
----------------------------------------
_The current status. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

After
----------------------------------------
_What has been changed. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

Technical Details
----------------------------------------
_If the PR introduces noteworthy technical changes, please describe them here. Provide code snippets if necessary_

Comments
----------------------------------------
_Anything else you would like the reviewer to note_

2019-06-05 16:08 UTC, pfigel requested changes
Aside from the `group_id` issue, this LGTM.

(*CiviCRM Review Template WORD-1.2*)

* General standards
    * ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain)) __PASS__
    * ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user)) __PASS__: No user impact, new API
    * ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc)) __PASS__
    * ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run)) __ISSUE__: group_id parameter is defined but not used to filter results. `r-run` successful otherwise, results match existing UI.
* Developer standards
    * ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech)) __PASS__: Doesn't change any behaviour. Allows decoupling / use of feature in extension.
    * ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code)) __PASS__
    * ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint)) __PASS__
    * ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test)) __PASS__

2019-06-05 16:08 UTC, pfigel commented on api/v3/Dedupe.php
> +  $params['group_id'] = [
Parameter is defined here, but not used as a filter in `civicrm_api3_dedupe_getduplicates`.

2019-06-05 21:59 UTC, eileenmcnaughton commented
Thanks @pfigel - I removed the 'group' parameter & enhanced the 'criteria' description to point out group can be included in the criteria (which I think is better since I don't think the underlying code really does need 2 filter methodologies)

2019-06-05 23:38 UTC, eileenmcnaughton commented
test this please

2019-06-06 01:36 UTC, eileenmcnaughton commented
test this please

2019-06-06 04:05 UTC, eileenmcnaughton commented
unrelated fail

2019-06-06 04:05 UTC, merged