Remove cached smart group entries when removing from a group
civicrm/civicrm-core pull request #14657
Opened 2019-06-27 13:26 UTC by eileenmcnaughton

Overview
----------------------------------------
Fixes a bug whereby removing a contact from a smart group does not take effect immediately when viewing the group

Before
----------------------------------------
Contact not dropped from group in search until the cache for the group ages out

After
----------------------------------------
Contact removed immediately

Technical Details
----------------------------------------
In 5.15 we have added fixes for smart groups regarding removed entries. Possibly related to this but also possibly pre-existing
I'm seeing contacts who have been removed from smart groups showing up after removal in search results for the duration of the smart group cache.

Regardless the fix feels safe, sensible and correct so I'm comfortable targetting the rc without further research as to whether it
is a regression. The fix being removal of the cache entry when the group entry is removed.

Comments
----------------------------------------

2019-06-27 13:38 UTC, mattwire requested changes
@eileenmcnaughton The fix itself is "correct".  However we should be using the existing function to do so.  Also, please take a look at https://github.com/mattwire/civicrm-groupaclcache/blob/master/CRM/Contact/BAO/GroupContact.php#L254 - calling `clearContactCaches()` is a bit overkill at this point and I replaced it with a group rebuild in my ACL cache rewrite - it will be a while before I can work on getting any more of that into core but there are lot's of improvements!

2019-06-27 13:38 UTC, mattwire commented on CRM/Contact/BAO/GroupContact.php
> +        ]);
We already have a function to do this in `GroupContactCache.php` - `CRM_Contact_BAO_GroupContactCache::removeContact()` - can we use that please?

2019-06-28 00:39 UTC, eileenmcnaughton commented
Thanks @mattwire - fixed. Maybe we can work through incorporating your work in Barcelona

2019-06-28 08:30 UTC, mattwire commented on CRM/Contact/BAO/GroupContact.php
> +        ]);
thanks

2019-06-28 08:31 UTC, mattwire approved these changes

2019-06-28 08:31 UTC, mattwire commented
Approved from a code POV and concept.  It just needs an r-run and we can merge

2019-06-28 22:16 UTC, seamuslee001 commented
I tested this on a dev box and confirmed the current behaviour. I made sure the case was filled up

```
mysql> SELECT * FROM civicrm_group_contact_cache;
+----+----------+------------+
| id | group_id | contact_id |
+----+----------+------------+
|  3 |        5 |         98 |
|  1 |        5 |        114 |
|  2 |        5 |        189 |
+----+----------+------------+
3 rows in set (0.00 sec)
```
Then i removed contact id 189 from the smart group and checked the cache again and nothing had changed
```

mysql> SELECT * FROM civicrm_group_contact_cache;
+----+----------+------------+
| id | group_id | contact_id |
+----+----------+------------+
|  3 |        5 |         98 |
|  1 |        5 |        114 |
|  2 |        5 |        189 |
+----+----------+------------+
3 rows in set (0.00 sec)
```
I then applied the patch and reset the group membership and checked the cache again

```
mysql> SELECT * FROM civicrm_group_contact_cache;
+----+----------+------------+
| id | group_id | contact_id |
+----+----------+------------+
|  3 |        5 |         98 |
|  1 |        5 |        114 |
|  2 |        5 |        189 |
+----+----------+------------+
3 rows in set (0.00 sec)
```
I then removed contact 189 again from the group and this time the cache was correctly updated instantly
```
mysql> SELECT * FROM civicrm_group_contact_cache;
+----+----------+------------+
| id | group_id | contact_id |
+----+----------+------------+
|  3 |        5 |         98 |
|  1 |        5 |        114 |
+----+----------+------------+
2 rows in set (0.00 sec)
```

2019-06-28 22:16 UTC, merged

2019-06-28 22:17 UTC, eileenmcnaughton commented
thanks @seamuslee001 & @mattwire for pointing out the better approach