dev/financial#82 revert added setters
civicrm/civicrm-core pull request #15707
Opened 2019-11-02 04:19 UTC by eileenmcnaughton

Overview
----------------------------------------
We added some structure to CRM_Core_Payment in the current unreleased code. However @artfulrobot has a proposal that @mattwire & I both agree is better architecture and less likely to break stuff.

I think the cleanest option here is to simply reverse these changes in 5.20 and do them again, better. I'd like the better to be in 5.20 but if we missed 5.20 I think it would not cause issues

Before
----------------------------------------
New but now deprecated methods in play

After
----------------------------------------
Slate cleaned to try again

Technical Details
----------------------------------------
@mattwire @artfulrobot

Comments
----------------------------------------

2019-11-04 21:19 UTC, eileenmcnaughton commented
@mattwire @artfulrobot - so merging this is priority 1 in my opinion - then we can finalised @artfulrobot's improved version - but we should get this merged before the rc is cut

2019-11-04 21:57 UTC, mattwire requested changes
@eileenmcnaughton I think there's a few bits in here (mostly comments) that should not be.

2019-11-04 21:57 UTC, mattwire commented on api/v3/PaymentProcessor.php
> +  return civicrm_api3_create_success(array($result), $params);
@eileenmcnaughton This shouldn't be in here

2019-11-04 21:57 UTC, mattwire commented on api/v3/PaymentProcessor.php
> +    'api.required' => 1,
@eileenmcnaughton This shouldn't be in here

2019-11-04 21:57 UTC, mattwire commented on tests/phpunit/api/v3/PaymentProcessorTest.php
> -   * @throws \CRM_Core_Exception
@eileenmcnaughton None of this needs to go?

2019-11-04 21:57 UTC, mattwire commented on api/v3/PaymentProcessor.php
> -  /* @var CRM_Core_Payment $processor */
@eileenmcnaughton Don't need to remove?

2019-11-04 21:57 UTC, mattwire commented on CRM/Core/Payment.php
> +   *
@eileenmcnaughton This doesn't need removing

2019-11-04 21:57 UTC, mattwire commented on CRM/Core/Payment.php
> +   * @var object
@eileenmcnaughton Don't think this should be in here

2019-11-04 22:08 UTC, eileenmcnaughton commented
@mattwire I've re-applied some of those changes in an extra commit - I think most of them are easy enough to re-spot / re-do

2019-11-04 23:27 UTC, mattwire approved these changes

2019-11-04 23:27 UTC, merged

2019-11-05 00:12 UTC, eileenmcnaughton commented
Thanks @mattwire  - @artfulrobot - where are we at with your alternative - it's still marked WIP but I think you possibly think it is review-ready