Fix for #1767: https://lab.civicrm.org/dev/core/-/issues/1767
civicrm/civicrm-core pull request #17361
Opened 2020-05-19 15:47 UTC by jaapjansma

Overview
----------------------------------------
This is a PR for an issue reported on lab. That issue also contained a solution and I have created the PR. As SRQ_Civicrm was not able to do so. So I helped him by providing the PR. 

The issue is wel documented on lab.

Before
----------------------------------------

The reg ex for finding duplicate phone numbers was wrong.

After
----------------------------------------

The reg ex has been changed a duplicate phone numbers would be found. 

Comments
----------------------------------------
See https://lab.civicrm.org/dev/core/-/issues/1767 for reproduction steps.

2020-05-19 16:13 UTC, colemanw commented on CRM/Dedupe/Finder.php
> +      if (preg_match('/(.\*)-(Primary-[\d+])$|(.\*)-(\d+-\d+)$|(.\*)-(\d+|Primary)$/', $key, $matches)) {
I don't understand the escaping of the star character here. What does that accomplish?

2020-05-20 01:04 UTC, colemanw requested changes
Needs updating per comments on gitlab

2020-05-20 07:35 UTC, jaapjansma commented
I have updated the PR

2020-06-08 10:12 UTC, jaapjansma commented
@colemanw are you able to merge this PR?

2020-07-18 09:06 UTC, eileenmcnaughton commented
Ok I managed to put aside some time for this & here is the test https://github.com/civicrm/civicrm-core/pull/17882 - I was able to replicate it in the test & now it has a test it is mergeable

2020-07-18 09:07 UTC, merged

2020-07-19 02:17 UTC, colemanw commented
Thanks for doing that @eileenmcnaughton

2020-07-19 22:49 UTC, eileenmcnaughton commented
@colemanw yeah - @jaapjansma had asked for help on this one so that got it high enough on the list to spend a evening on it