Contribution confirmation page should not display the name of payment processor type
civicrm/civicrm-core pull request #17568
Opened 2020-06-10 06:04 UTC by agileware-pengyi

Overview
----------------------------------------
The name of the payment processor type is displayed on the confirmation page. That is not needed.

Before
----------------------------------------
The text is **Click the Continue button to go to PayPal_Standard, where you will select your payment method and complete the contribution.**
![confirm-page](https://user-images.githubusercontent.com/49378827/84232103-ed874080-ab32-11ea-955b-07b4eb9cb7f8.png)

After
----------------------------------------
The text is **Click the Continue button to complete the contribution.**

Comments
----------------------------------------
A fixed text is good enough.
It can display the name/title of the payment processor instance, however, there is no description on the payment processor settings page says the field will be displayed publicly and the site admin has to update it.

Gitlab ref: https://lab.civicrm.org/dev/financial/-/issues/134

Agileware ref: CIVICRM-1496

2020-06-18 13:50 UTC, yashodha commented
@agileware-pengyi 

Can you please incorporate Eileen's feedback so that we can merge this?

2020-06-19 02:13 UTC, agileware-justin requested changes

2020-06-19 02:13 UTC, agileware-justin commented on CRM/Core/Payment.php
>            return ts('To complete this transaction, click the <strong>Continue</strong> button below.');
Recommend removing this line and logic entirely.

2020-06-19 02:13 UTC, agileware-justin commented on CRM/Core/Payment.php
>          if ($this->_paymentProcessor['billing_mode'] == 4) {
Remove this logic

2020-06-19 02:13 UTC, agileware-justin commented on CRM/Core/Payment.php
> +          return ts('Click the <strong>Continue</strong> button to complete the contribution.');
OK with changing text to: "button to proceed with the contribution" - minor text change

2020-06-19 02:13 UTC, agileware-justin commented on CRM/Core/Payment.php
>          if ($params['is_payment_to_existing']) {
This logic and return text is essentially the same as the others, so just remove it.

2020-06-19 02:13 UTC, agileware-justin commented on CRM/Core/Payment.php
>            return ts('To complete this transaction, click the <strong>Make Payment</strong> button below.');
And then below this we have a catch-all return text, which again is essentially the same. So just have a single catch-all return text, remove all other logic.

Makes things much simpler.

2020-06-19 02:13 UTC, agileware-justin commented
> 1. add the getText function to the Paypalimpl file, overriding the parent function & move this the

@eileenmcnaughton but why do this? Don't we want to reduce the complexity and technical debt, not add more?

2020-06-19 02:15 UTC, agileware-justin commented
@yashodha there's a lot of redundant logic and various for the same return message in this case statement, look beyond what this PR to change and you'll see quite a confusing mess.

2020-06-19 02:18 UTC, eileenmcnaughton commented
@agileware-justin - so the wording exists because obviously people thought it was much clearer in the context of Paypal & it's in the Core_Payment class because paypal logic used to be pretty much everywhere.

We now have 2 possibilities
1) the wording belongs to paypal & makes sense there - in which case our model is the Paypal class overrides the parent & puts it it's specific wording 

OR
2) people generally agree that we can change the wording without it being less clear to paypal users - in which case we need some broader buy in on that as a User experience change

2020-06-19 03:17 UTC, agileware-justin commented
@eileenmcnaughton did you see that the same user-facing text is repeated 4 times?

2020-06-19 03:21 UTC, eileenmcnaughton commented
If we can add an after screenshot then we can ping some other people & check they are comfortable with the text change. Obviously the text was done like that because someone decided it was more logical for the user experience. I don't have strong opinion as to whether it is or not but need to see that others agree before changing as people often care about this sort of thing.

2020-06-19 03:29 UTC, agileware-justin commented
> Can you please incorporate Eileen's feedback so that we can merge this?

So if we had done your changes then this would have been merged.
But now it needs approval and buy-in from others, OK @eileenmcnaughton - no worries.

I do genuinely want to know if have reviewed this section of the code and seen the redundant logic which is used to essentially repeat variations of the same message to the user.

It's like this section of code has been edited by multiple people without scrolling up or down beyond the lines of their work and may not have understood that the words used in their message text are essentially the same.

2020-06-19 03:31 UTC, eileenmcnaughton commented
@agileware-justin so the changes I suggested - basically overriding the function in the paypal code would have meant the text didn't change - just the word paypal was fixed - in that case it just fixes a bug.

For an actual text change I wouldn't take it on myself to merge without ensuring others agree

2020-06-19 03:32 UTC, eileenmcnaughton commented
(& re the code -I have s really focussed on the above - ie. determining if a text change is being made or just the wrong word is being fixed - I haven't done a code review on this at this stage)

2020-06-19 03:33 UTC, agileware-justin commented
@eileenmcnaughton all good, love your work as always :)

2020-06-19 13:22 UTC, mlutfy commented
Personally I'm all for simplifying, but would it be possible to clarify the PR description to fully reflect the changes before/after?

For example, there are comments about "remove this code if amount < 0". Why? What?

(I don't object, I just don't understand the code comments, and the before/after, and what was really changed.)

I personally don't like the confirmation pages, but I can understand confused users, if it says "click to complete your contribution", but they haven't entered any payment details yet. Can't we display the "Payment Processor label" (which was added a few releases ago?)

2020-09-04 19:01 UTC, MegaphoneJon commented
@agileware-justin You don't have a screenshot handy of the repeated text, do you?  I don't think I have and PayPal Std clients at present.

2020-09-05 00:15 UTC, agileware-justin commented
> Personally I'm all for simplifying, but would it be possible to clarify the PR description to fully reflect the changes before/after?

@mlutfy only the author can edit the PR text - github permissions

> For example, there are comments about "remove this code if amount < 0". Why? What?
> (I don't object, I just don't understand the code comments, and the before/after, and what was really changed.)

This section of code has redundant logic which is used to repeat variations of the same instructions to the user. Let me illustrate:
1. Repeat the same instructions
2. Same instructions are repeated
3. The instructions are the same
4. Makes no sense, why are the instructions the same?

To be honest, I would just display "Pay now" as a button and not have any text at all. But that's too controversial a change :)

> I personally don't like the confirmation pages, but I can understand confused users, if it says "click to complete your contribution", but they haven't entered any payment details yet. Can't we display the "Payment Processor label" (which was added a few releases ago?)

"Payment Processor label" is an optional field, so it cannot be relied upon to be set.

> You don't have a screenshot handy of the repeated text, do you? I don't think I have and PayPal Std clients at present.

@MegaphoneJon I'm not sure what screenshot you want to see. The repeated text we're trying to remove is visible here on the left hand side of the change, https://github.com/civicrm/civicrm-core/pull/17568/files

2020-10-15 00:01 UTC, eileenmcnaughton commented
We discussed this today (@seamuslee001 @kcristiano @jusfreeman  + me) & a version of the text was agreed. @jusfreeman will update & @seamuslee001 will merge (based on him having paid more attention to the final agreement than me )

2020-10-15 07:02 UTC, agileware-justin commented
@seamuslee001 ready to merge when you are mate!

2020-10-15 23:52 UTC, merged