[REF] Extract function to get locations to merge, rename 'operation' …
civicrm/civicrm-core pull request #17991
Opened 2020-07-29 06:57 UTC by eileenmcnaughton

…to is_replace'

This is a preliminary refactor. I have a bug to fix in this code but cannot yet make sense of it. The mergeHandler class
is simply an object to refactor the functions onto. Much of this code is hard to work with as the use of static functions
necessitates a lot of compilation and compiling so the process of cleaning it up involves extracting functionns to this
new class (which may one day replace the Merger class). As it is a refactoring process the functions reflect the old code
more than the ideal code. However, it provides the change to give some documentation regarding the locBlock array
and also to rename the confusing field 'operation' to 'is_replace'

Overview
----------------------------------------
_A brief description of the pull request. Keep technical jargon to a minimum. Hyperlink relevant discussions._

Before
----------------------------------------
_What is the old user-interface or technical-contract (as appropriate)?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

After
----------------------------------------
_What changed? What is new old user-interface or technical-contract?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

Technical Details
----------------------------------------
_If the PR involves technical details/changes/considerations which would not be manifest to a casual developer skimming the above sections, please describe the details here._

Comments
----------------------------------------
_Anything else you would like the reviewer to note_

2020-07-29 08:19 UTC, eileenmcnaughton commented
more work to do - will re-open when not WIP

2020-07-29 08:20 UTC, eileenmcnaughton commented
Actually test fails were due to WIP not in this commit

2020-07-29 10:59 UTC, eileenmcnaughton commented
unrelated fail

2020-07-31 23:33 UTC, eileenmcnaughton commented
test this please

2020-08-02 06:29 UTC, eileenmcnaughton commented
test this please

2020-08-03 01:27 UTC, eileenmcnaughton commented
test this please

2020-08-19 16:18 UTC, pfigel requested changes
@eileenmcnaughton this seems to cause the "Add new" checkbox to not be respected when merging, i.e. for two contacts with two "Home" emails and "Add new" being selected, it overwrites the existing email of to_keep's contact with to_remove's.

2020-08-19 21:25 UTC, eileenmcnaughton commented
ouch! Thanks @pfigel I will re-visit

2020-08-28 04:23 UTC, eileenmcnaughton commented
@pfigel not sure you saw the ping - are you able to recheck this?

2020-08-30 18:48 UTC, pfigel approved these changes
@eileenmcnaughton sorry, must have missed this. Did another round of testing, looks good now!

* General standards
    * ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain)) __PASS__
    * ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user)) __PASS__: No user impact
    * ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc)) __PASS__
    * ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run)) __PASS__: Found no regressions related to location type merging behaviour, no issues with merging in general.
* Developer standards
    * ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech)) __PASS__: One method with signature change, no matches in universe and unlikely to be called directly outside of core.
    * ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code)) __PASS__
    * ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint)) __PASS__
    * ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test)) __PASS__

2020-08-30 20:08 UTC, merged