Handle checking smartgroups when generating list of groups to unsubscribe
civicrm/civicrm-core pull request #21176
Opened 2021-08-18 20:07 UTC by mattwire

Overview
----------------------------------------
The unsubscribe form doesn't check if you've already unsubscribed from a smartgroup so it looks like it doesn't work when you do so because it always shows the smartgroups as available for unsubscribe.  That's not a very good user experience, especially as for many users this will be their last interaction with the organisation.

Before
----------------------------------------
Always shows this first page if there are unsubscribable smartgroups even if the user has already unsubscribed from those groups:
![image](https://user-images.githubusercontent.com/2052161/129964692-5176e7b9-f09b-4fbe-8ecd-4b27e4dfb038.png)

After
----------------------------------------
Only shows the first page if there are groups/smartgroups that the user is still a member of. Otherwise just displays a message that they've already unsubscribed.

Technical Details
----------------------------------------
"Borrows" from CiviRules and elsewhere. We check (and refresh if necessary) the groups to make sure we have an up to date group contact cache. Then we run a query that checks both `civicrm_group_contact` and `civicrm_group_contact_cache`.

Comments
----------------------------------------

2021-08-19 02:36 UTC, seamuslee001 commented
So thinking about this from a performance POV, smart groups aren't always that performant, that having being said we are limited to a very select number of groups so I think we would be ok, but might be worth getting someone like @johntwyman to look at this one

2021-08-19 09:26 UTC, mattwire commented
@seamuslee001 I was a bit concerned about any performance impact but I don't think it should be that bad because:
- smartgroup is only rebuilt if cache time has expired.
- rebuild will only be triggered if someone clicks the unsubscribe link
- if multiple users click the unsubscribe link at a similar time it's likely they'll be subscribed to the same groups so should only trigger one or two rebuilds of expired smartgroups.
- can only happen after a mailing has been sent.

2021-09-07 11:49 UTC, mlutfy commented
There are days where I wish we did not allow Smart Groups to be used as mailing groups. People abuse it and it gives really odd results like this (I was testing an unsubscribe from the "Campfire" mailings):

![unsubscribe-2021-09-06_14-16](https://user-images.githubusercontent.com/254741/132339049-0abf2a57-c542-47f7-ae07-dd8a1213f99e.png)

(ignore the meme, I was confused at the form re-appearing after having unsubscribed, other issue)

That said - if people do abuse of smartgroups, then I think merging this is the right thing to do.

2021-09-07 19:06 UTC, kurund requested changes
@mattwire 
Just added some minor formatting changes and removed extra ;

2021-09-07 19:06 UTC, kurund commented on CRM/Mailing/Event/BAO/Unsubscribe.php
> +                LEFT JOIN civicrm_group_contact_cache gcc
```suggestion
            LEFT JOIN     civicrm_group_contact_cache gcc
```

2021-09-07 19:06 UTC, kurund commented on CRM/Mailing/Event/BAO/Unsubscribe.php
> +                        ) GROUP BY grp.id;";
```suggestion
                        ) GROUP BY grp.id";
```

2021-09-07 19:11 UTC, kurund commented
@mattwire @seamuslee001 

This fix make sense to me.  I also think it won't have major impact on performance due to smart group rebuilding etc for the reasons mentioned above.

I have tested the patch and it is working as expected.

2021-09-07 19:29 UTC, mattwire commented
Thanks @kurund I've committed your suggestions and squashed commits

2021-09-07 19:53 UTC, mlutfy commented
@seamuslee001 @johntwyman Any final thoughts? Need more time?

2021-09-07 23:52 UTC, johntwyman commented
Thanks for the invitation to give this some thought. On balance I think improving the user experience trumps the performance cost of recalculating smart group membership. I am somewhat concerned about that for an installation like ours but the reality is we're the creators of our own misfortune in many regards. ;-)

2021-10-20 13:04 UTC, mattwire commented
@kurund For me yes!

2021-10-22 14:55 UTC, merged

2022-01-07 14:09 UTC, tommybobo commented
I am leaving this here for anyone else stuck in a pickle. 

So this change just crashed site yesterday and the day before, It is yes a mess of their own making but also I think a key performance issue was over looked. I have noticed that a rise in enterprise level mail servers having bots check and scan links in emails. When a large list is emailed with a large number of enterprise emails, those bots quickly check every link including the unsubscribe link. So we found a site basically crippled by trying to send out on an email while this unsubscribe look up was being run 20ish times a minute. And stalling out because the links were being clicked nearly simultaneously and thus seeming to regenerate the cache simultaneously. Also while the link bots were loading pages, logging clicks, and the next batch of emails were being sent.

We are looking into ways to circumvent this pile up. In the meantime we are increasing the cache timeout, using only Opt Out of all, and throttling outbound emails significantly.

2022-01-13 21:09 UTC, eileenmcnaughton commented
Regression logged against this https://lab.civicrm.org/dev/core/-/issues/3031

Performance impact was discussed in this ticket earlier but it was said that 

"smartgroup is only rebuilt if cache time has expired."

It is more correct to say 'smartgroups are rebuilt for ALL groups whose cache time has expired' - in the case of AUG I would think that would be a couple of thousand groups - which is why we previously removed most loadAll calls from the code