Fix return values for API3 Job.delete
civicrm/civicrm-core pull request #22561
Opened 2022-01-18 10:53 UTC by mattwire

Overview
----------------------------------------

Before
----------------------------------------
API3 Job.delete missing return values

After
----------------------------------------
API3 Job.delete has standard return values.

Technical Details
----------------------------------------

Comments
----------------------------------------

2022-01-18 15:11 UTC, colemanw requested changes

2022-01-18 16:17 UTC, mattwire commented on CRM/Core/ManagedEntities.php
> +        $result = civicrm_api3($dao->entity_type, 'delete', $params);
@colemanw Ah ok did not realise. We don't actually need this change anyway so have removed from the commit

2022-01-18 16:52 UTC, colemanw approved these changes

2022-01-18 22:45 UTC, mattwire commented
test this please

2022-01-20 18:40 UTC, mattwire commented
Merging based on @colemanw approval and tests passing

2022-01-20 18:40 UTC, merged