Afform - Implement client-side validation of required fields
civicrm/civicrm-core pull request #23604
Opened 2022-05-26 21:07 UTC by colemanw

Overview
----------------------------------------
This is (so far) a client-side only implementation of required field validation for Afforms.

Before
----------------------------------------
Required fields not required.

After
----------------------------------------
![image](https://user-images.githubusercontent.com/2874912/170580321-401cb4f2-9320-4d90-a35f-130cf2795b96.png)

2022-06-22 16:37 UTC, MegaphoneJon commented on ext/afform/core/ang/af/afForm.component.js
> +            _.each(ctrl.fileUploader.getNotUploadedItegitk&ms(), function(file) {
This looks unintentional.

2022-06-23 00:18 UTC, colemanw commented on ext/afform/core/ang/af/afForm.component.js
> +            _.each(ctrl.fileUploader.getNotUploadedItegitk&ms(), function(file) {
Oopa

2022-06-27 17:48 UTC, kurund requested changes
@colemanw 

Required validation seems to be working fine on backend and frontend for standard fields.

It needs to be fixed for block like Email block.

2022-07-08 18:11 UTC, aydun commented
It's working for fields from the standard entities but not for fields from my custom entity.  The fields show as required on the builder page but not on the display page.  

To test with a custom entity, see https://lab.civicrm.org/dev/core/-/issues/3728

2022-07-28 09:47 UTC, eileenmcnaughton commented
@colemanw this needs a rebase - also not quite sure status otherwise but can get @kurund to recheck once it is not stale

2022-07-28 18:02 UTC, colemanw commented
I've rebased this @eileenmcnaughton @kurund

2022-08-01 09:52 UTC, kurund commented
@colemanw 

Below is the sample form with all the fields configured as required in the Formbuilder.
![Screenshot from 2022-08-01 10-48-16](https://user-images.githubusercontent.com/151481/182122096-f7e469d1-8cd8-489e-b383-b8ff3da73162.png)

However, I was able to submit the form by filling only data in the above screenshot.

2022-08-26 16:38 UTC, kurund commented
@colemanw 

It looks like "required" param is missing in field definition for 'joins'. You can check the generated code. Hence, I the email validation is failing.

2022-09-03 02:59 UTC, colemanw commented
@kurund I've fixed setting default required value for e.g. Email joins.
I think there's still some issue with Select2, but maybe this is good enough to merge now and we can investigate Select2 in a different PR.

2022-09-05 15:39 UTC, kurund approved these changes
Looks good to me. ready to for merging.

TODO for separate PR
- Select2 fields
- RichText fields

2022-09-05 16:01 UTC, merged