Adds Profiles to civicrm_admin_ui
civicrm/civicrm-core pull request #24725
Opened 2022-10-12 13:04 UTC by AlainBenbassat

Overview
----------------------------------------
Adds Profiles to civicrm_admin_ui.

Before
----------------------------------------
Quickform admin screens for profiles and profile fields.

After
----------------------------------------
Search Kit + Afform to manage profiles and profile fields.

Comments
----------------------------------------
- I could not display the "Used for" in the profile admin screen because there are no pseudoconstants for that.
- I could not add the help text behind the question mark in the profile admin screen.

2022-10-13 10:13 UTC, Damilare1 requested changes
Hi @AlainBenbassat, thanks for working on this. I dropped comments on some places I believe could do with some internationalisation using the CRM_CivicrmAdminUi_ExtensionUtil class.

2022-10-13 10:13 UTC, Damilare1 commented on ext/civicrm_admin_ui/ang/afsearchProfileFields.aff.json
> +        "label": "Profile Fields",
We need to add internalisation to the label and text strings.

2022-10-13 10:13 UTC, Damilare1 commented on ext/civicrm_admin_ui/managed/SavedSearch_Administer_Profiles.mgd.php
> +        'label' => 'Administer Profiles',
We need to add internalisation to the label and text strings.

2022-10-15 21:58 UTC, colemanw commented
I've pushed up some additional changes to this, and I think it's close enough to parity with the original form to be merged at this point.

2022-10-17 15:06 UTC, merged

2022-10-17 15:08 UTC, AlainBenbassat commented
Thank you @colemanw for finishing my work.

2022-10-17 15:27 UTC, colemanw commented
No problem @AlainBenbassat  - perhaps you could take a moment to leave a review on #24759 :)

2023-04-22 02:26 UTC, larssandergreen commented
I believe there is a bit of an issue with how the redirection on adding a profile and the breadcrumbs work in this change, [issue here (#4254).](https://lab.civicrm.org/dev/core/-/issues/4254)