dev/core#4144 Fix smarty notice on isDuplicate
civicrm/civicrm-core pull request #25657
Opened 2023-02-23 23:59 UTC by eileenmcnaughton

Overview
----------------------------------------
dev/core#4144 Fix smarty notice on isDuplicate

Before
----------------------------------------
_What is the old user-interface or technical-contract (as appropriate)?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

After
----------------------------------------
_What changed? What is new old user-interface or technical-contract?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

Technical Details
----------------------------------------
_If the PR involves technical details/changes/considerations which would not be manifest to a casual developer skimming the above sections, please describe the details here._

Comments
----------------------------------------
_Anything else you would like the reviewer to note_

2023-02-24 00:02 UTC, eileenmcnaughton commented on CRM/Profile/Form.php
> -  protected $_duplicateButtonName;
this just muddies the waters using a property

2023-03-08 00:57 UTC, eileenmcnaughton commented
This passed but I rebased to keep it fresh - seems like an infra issue test this please

2023-03-10 19:12 UTC, highfalutin requested changes
The template could use one more little change to simplify it further

2023-03-10 19:26 UTC, highfalutin commented
Now trying to do a run, but I can't find where to trigger these notices. What form should I go to?

2023-03-10 21:54 UTC, eileenmcnaughton commented
@highfalutin they occur when using profiles - I'm not sure how intolerant your set up has to be but I saw another php 8.x user try to fix it & I definitely see it when I turn on smarty hardening - https://docs.civicrm.org/dev/en/latest/security/outputs/#html

2023-03-10 21:55 UTC, eileenmcnaughton commented on templates/CRM/Profile/Form/Dynamic.tpl
> +  {if array_key_exists('_qf_Edit_upload_duplicate', $form) && $isDuplicate}
@highfalutin the reason for the button check is that the button is ONLY there under a very narrow situation - if you use an entity reference field & choose (e.g) new Organization AND choose an organization that exists THEN the button appears

2023-03-11 00:45 UTC, highfalutin commented
OK, for me the notices only show up if I view the form in its own tab, instead of as a modal.

Smarty hardening doesn't need to be turned on for the notices to appear.

Side note: I was a bit confused by the mention of "entity reference" -- the special "New Individual" and "New Organization" links don't appear on Entity Reference/Contact Reference custom fields, only on built-in fields built with `CRM_Core_Form::addEntityRef()`... but anyway that turns out to be a red herring. The smarty notices actually seem to appear on any profile used in standalone Create/Edit mode, it doesn't really matter how you get to them.

### Before
Open a profile edit page like `civicrm/profile/create&reset=1&gid=xxxxx` where `xxxxx` is the id of any profile which can be used in standalone create/edit mode.

Several notices appear, including:

````
Warning: Undefined array key "isDuplicate" in /path/to/civi.files/templates_c/en_US/%%0A/0AF/0AF6F87E%%Dynamic.tpl.php on line 35
Warning: Undefined array key "isDuplicate" in /path/to/civi.files/templates_c/en_US/%%0A/0AF/0AF6F87E%%Dynamic.tpl.php on line 86
````

The same notices appear when `&context=dialog` is added to the url, telling Civi that the output is intended for a modal dialog box.

### After
In `dialog` context, both notices disappear. In non-`dialog` context, the notice about line 35 disappears but the one about line 86 remains.

To get both lines to disappear in both contexts:

````patch
diff --git a/CRM/Profile/Form.php b/CRM/Profile/Form.php
index 5bb2cf99d8..e8c8d9bdc4 100644
--- a/CRM/Profile/Form.php
+++ b/CRM/Profile/Form.php
@@ -904,10 +904,11 @@ class CRM_Profile_Form extends CRM_Core_Form {
       $this->freeze();
     }

+    // Assign FALSE, here - this is overwritten during form validation
+    // if duplicates are found during submit.
+    CRM_Core_Smarty::singleton()->assign('isDuplicate', FALSE);
+
     if ($this->isEntityReferenceContactCreateMode()) {
-      // Assign FALSE, here - this is overwritten during form validation
-      // if duplicates are found during submit.
-      CRM_Core_Smarty::singleton()->assign('isDuplicate', FALSE);
       $this->addElement(
         'xbutton',
         $this->getButtonName('upload', 'duplicate'),
````

I also took out the `array_key_exists('_qf_Edit_upload_duplicate', $form) && ` from the template, and confirmed that everything works fine without it. `$isDuplicate` should be renamed to `$showSaveDuplicateButton` because that's really what it's about.

2023-03-11 00:52 UTC, eileenmcnaughton commented
Thanks @highfalutin  - I'll make the changes you suggest once I have fulfilled my chauffeur duties...

2023-03-11 01:01 UTC, highfalutin commented
just made a PR to your PR 😆

2023-03-11 02:11 UTC, eileenmcnaughton commented
OH wow - I got sooo confused - I thought your PR was against master & then I thought this must be already merged but then it wasn't and then my son sang 'I'm Slim Shady' & my brain broke

2023-03-11 02:12 UTC, eileenmcnaughton commented
I've given the merge-on-pass based on the review / collaboration from @highfalutin

2023-03-11 02:39 UTC, highfalutin commented
@eileen we'll have to credit Eminem in the next release 🤣

2023-03-11 03:30 UTC, eileenmcnaughton commented
lol

2023-03-11 03:31 UTC, merged