dev/core#5520 - Fix SearchKit DB entity displays with long names
civicrm/civicrm-core pull request #31360
Opened 2024-10-24 13:41 UTC by colemanw

Overview
----------------------------------------
Fixes https://lab.civicrm.org/dev/core/-/issues/5520

Technical Details
----------------------------------------
Some versions of SQL require a maxlength of 64 characters per column.

This will append a hash of the full name to trimmed names to keep them unique but predictable.

2024-10-31 13:53 UTC, pfigel requested changes
`r-run` shows that the column name is successfully truncated (resulting in something like `Long_Custom_Group_Name_An_Even_Longer_Field_Namee6d14111f47cca08`), but it is then used by `CRM_Core_BAO_SchemaHandler::buildSearchIndexSQL()` as part of the index name (which includes a prefix), i.e. something like `index_Long_Custom_Group_Name_An_Even_Longer_Field_Namee6d14111f47cca08`. These also seem to have a 64-character limit.

`CRM_Core_BAO_SchemaHandler::buildSearchIndexSQL()` should probably just use `CRM_Core_BAO_SchemaHandler::getIndexName()`.

Full DDL produced during `r-run`:
```sql
CREATE TABLE civicrm_sk_contact_search_by_standalone_admin_db_entity1 (
        `_row` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Row number',
        `id` int(10) unsigned NULL,
        `Long_Custom_Group_Name_An_Even_Longer_Field_Namee6d14111f47cca08` varchar(255) NULL,
        PRIMARY KEY ( _row ),
        INDEX index_id ( id ),
        INDEX index_Long_Custom_Group_Name_An_Even_Longer_Field_Namee6d14111f47cca08 ( Long_Custom_Group_Name_An_Even_Longer_Field_Namee6d14111f47cca08 )
) ENGINE=InnoDB ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
```

2024-10-31 13:59 UTC, colemanw commented
Thanks for the review @pfigel. I've updated it to limit to 58 instead of 64, which should leave room for the 6 characters in "index_".

2024-10-31 14:13 UTC, pfigel approved these changes
`r-run` was successful now, LGTM!

2024-11-01 00:17 UTC, colemanw commented
@civicrm-builder retest this please

2024-11-07 03:56 UTC, merged