'Contains' operation for searching multi-select custom fields with the API.
civicrm/civicrm-core pull request #6612
Opened 2015-08-27 20:48 UTC by johanv

I had to rebase this on my PR for CRM-17101 (#6611).

I implemented a 'contains' operator for searching values in multi-select custom fields.
I'm not sure whether this is a useful enhancement for the API, I'll leave that to you. It covers my use case, so I might as well upload it :-)

2015-08-28 14:16 UTC, colemanw commented
One question I have about this is what happens if you try to use the CONTAINS operator on a non-multivalued field?
I'm guessing it won't work. Also, from your description, the LIKE operator won't work on a multivalued field.
So just a thought, but instead of inventing a new sql verb, maybe we could just get the LIKE operator to work correctly for multivalued fields using this code when appropriate?

2015-08-28 19:18 UTC, johanv commented
> what happens if you try to use the CONTAINS operator on a non-multivalued field?
> I'm guessing it won't work.

It won't work. Just like when you use a = operator on a multivalued field, that won't work either. Maybe we should throw an exception in both cases.

> So just a thought, but instead of inventing a new sql verb, maybe we could just get the LIKE operator to work correctly for multivalued fields using this code when appropriate?

When I am interested in entities that have some value selected in a multi-select custom field, I prefer to write

    'custom_15' => array('CONTAINS' => 'FI')

instead of

    'custom_15' => array('LIKE' => '%' . CRM_Core_DAO::VALUE_SEPARATOR . "FI" . CRM_Core_DAO::VALUE_SEPARATOR . '%')

Besides, the consumer of the API should not have to care about how multi-select custom fields are implemented. IMO, you should be able to use the API without needing CRM_Core_DAO::VALUE_SEPARATOR.

2015-08-28 19:21 UTC, colemanw commented
>  IMO, you should be able to use the API without needing CRM_Core_DAO::VALUE_SEPARATOR.

Absolutely agree. My suggestion was actually to make

    'custom_15' => array('LIKE' => 'FI')

work correctly using your code, which would imo make the api a bit more transparent, since you would be able to use the same verb on either single or multi-valued fields, and not have to care about how the api works internally.

2015-08-28 19:21 UTC, totten commented
Agree that it's really good to hide `VALUE_SEPARATOR` / implementation-details from the API consumer.

2015-08-28 19:22 UTC, totten commented
The semantics of "LIKE=>FI" are different from "CONTAINS=>FI". You would expect that "LIKE=>FI" matches a record with value "FIDO", but "CONTAINS=>FI" should not match "FIDO".

2015-08-28 19:23 UTC, johanv commented
Using 

    'custom_15' => array('LIKE' => 'FI')

can cause problems when one option value is a substring of another one. Which seems bad practice, I agree, but it is not impossible to define it like that.

2015-08-28 19:39 UTC, totten commented on tests/phpunit/api/v3/RelationshipTest.php
> +    // Clean up first, then assert.
It looks like this dealing with the edge-case where the test fails -- you still need to cleanup even if there's a failure.

As a nitpick for future reference (not worth a special project on its own, but something for any readers to note for the future)... there's still a risk that other parts will fail (eg callApiSuccess() in L478 could throw an exception). This pattern should be a bit safer:

```php
function testFoo() {
  $this->custom['foo'] =  $this->callApiSuccess('CustomField', 'Create', ...);
   ...
}
function tearDown() {
   foreach (array_reverse($this->custom) as $field) {
    $this->callApi('CustomField', 'Delete', ...);
   }
}

2015-08-28 19:40 UTC, totten commented
The PR adds a feature -- and includes unit-tests! What bliss!

2015-08-28 20:18 UTC, colemanw commented
Ok, not trying to hold up this excellent contribution, just think it through a bit. To clarify a minor misconception above, the api does not automatically append wildcards, so if you have a single-valued field `custom_1` with options `['BE', 'BEE', 'BEER']` you could do:

    'custom_1' => array('LIKE' => 'BE')

and it would only return fields with value "BE" (not BEE or BEER).  Whereas if you entered

    'custom_1' => array('LIKE' => 'BE%')

you'd get results with any of the three options. Well and good.

Now for a multivalued field. Say `custom_2` has options `['one', 'two', 'three']`. Records might contain any combination of these options, so how to search for them? Some ideas:

1. To find empty records:

    'custom_2' => ''

2. To find records that contain only 'two':

    'custom_2' => array("LIKE" => 'two')

3. To find records that contain the option 'one' (among others perhaps)

    'custom_2' => array('CONTAINS' => 'one')

4. To find records that contain one and two (perhaps three as well)

    'custom_2' => array('CONTAINS' => array('one', 'two'))

5. To find records that are exactly one and two (not three)

    'custom_2' => array("LIKE" => array('one', 'two'))

6. To find records that contain one _or_ two:

    ???

So I think this PR fits into that overall picture, adding the 3rd syntax. The others, afaik, are still missing. Note: I've backtracked on using "LIKE" and "CONTAINS" interchangeably because it doesn't carry exactly the same meaning. Thoughts?

2015-08-28 20:27 UTC, totten commented
I like the idea of differentiating (a) exact matches (2+5) and (b) partial matches (3+4+6).

For exact matches, `=` or `IS` might be more intuitive.

Or, if we wanted nomenclature that's got more symmetry to it, maybe verbs `CONTAINS-ALL`, `CONTAINS-ANY`, `CONTAINS-EXACTLY`?

2015-08-29 19:27 UTC, johanv commented
The PR [should also implement (4)](https://github.com/civicrm/civicrm-core/pull/6612/files#diff-6329da386c1213c4300469cf93a3d00cR2340), but I did not test this yet. I did it this way, because usually when you combine filters in the API, they are combined with 'AND'.

No matter what syntax we'll end up using, I think the cases @colemanw listed out are a good basis for the documentation of all this.

p.s.: I always forget to add wildcards in my sql like-expressions as well ;-)

2015-08-31 09:02 UTC, monishdeb commented
As per the 6 cases listed by @colemanw we can resolve the same treating value(s) as pattern for RLIKE eventually, as we are already doing in case of n-nary operators https://github.com/civicrm/civicrm-core/blob/4.6/CRM/Core/BAO/CustomQuery.php#L404, and in this way it will satisfy all the 6 cases as follows :-  

1.  'custom_2' => ''
Already we have a EMPTY pseudo-operator for this (EMPTY => 1)

2.  'custom_2' => array("LIKE" => 'two')
get build into   'custom_2' RLIKE '[[:<:]]two[[:>:]]'

3. 'custom_2' => array('CONTAINS' => 'one')
build into 'custom_2' RLIKE '[[:ctrl:]]*two[[:ctrl:]]*'

4. 'custom_2' => array('CONTAINS' => array('one', 'two')) 
build into 'custom_2' RLIKE '[[:ctrl:]]*one[[:ctrl:]]two[[:ctrl:]]*'

5. 'custom_2' => array("LIKE" => array('one', 'two'))
 build into   'custom_2' RLIKE '[[:<:]]one[[:ctrl:]]two[[:>:]]'

6. To find records that contain one or two: 'custom_2' => array('IN' => array('one', 'two'), 'wildcard' => 1)
as per https://github.com/civicrm/civicrm-core/blob/4.6/CRM/Core/BAO/CustomQuery.php#L406 it will build into   'custom_2' RLIKE '[[:cntrl:]]*one[[:cntrl:]]|[[:cntrl:]]*two[[:cntrl:]]*'

So as per the changes we don't need to use to wildcard '%' (as value may itself contain '%' though seems peculiar) but the api param should be formatted in way that it will support 'wildcard as key' option along with 'operator as key' like mentioned in 6. On otherhand I think such special multi-value custom field that uses special character as n sperator should be handled via regex pattern so handle special scenario like in (1+5).

2015-08-31 09:50 UTC, johanv commented
I am not familiar with rlike, but suppose that custom_2 would have options `['one', 'one-b', 'two']` selected, would this still work?

> `'custom_2' => array('CONTAINS' => array('one', 'two'))`
> build into `'custom_2' RLIKE '[[:ctrl:]]*one[[:ctrl:]]two[[:ctrl:]]*'`

And what about

    'custom_2' => array('CONTAINS' => array('two', 'one'))

?

2015-08-31 11:17 UTC, monishdeb commented
Yes it does. 
Lets for example these are the multi-value records in custom table 
![total-values](https://cloud.githubusercontent.com/assets/3735621/9577527/44dcdeb0-4fff-11e5-88a9-c668178a3a64.png)
As per your query 'custom_2' => array('CONTAINS' => array('one')) it will return 
![tregex](https://cloud.githubusercontent.com/assets/3735621/9577554/b51fad60-4fff-11e5-9741-f6f3a0885d44.png)

2015-08-31 12:01 UTC, monishdeb commented
@johanv I have updated case 4 `'custom_2' => array('CONTAINS' => array('one', 'two'))` build clause as it was wrong earlier

2016-06-20 15:46 UTC, JoeMurray commented
@digitlimit would you be interested in reviewing this patch?

2016-09-26 16:31 UTC, colemanw requested changes
Looks like this PR needs additional work before merging.

2017-04-25 09:22 UTC, jitendrapurohit commented
@eileenmcnaughton Can we close this as it hasn't progressed from more than a year? Also, one can always re-open this when anyone feels to work on it?

2017-04-25 09:27 UTC, eileenmcnaughton commented
Yes - I agree - this might be part of apiv4 ....I'll make sure there IS a link on the JIRA so all this good discussion / work is still accessible

2017-04-25 09:27 UTC, closed without merging