Drupal 7 getLoginURL Fix
civicrm/civicrm-core pull request #8950
Opened 2016-08-30 07:25 UTC by garethdylan361

Drupal 7 getLoginURL was not supplying the base url.

2016-08-30 07:25 UTC, civicrm-builder commented
Can one of the admins verify this patch?

2016-08-30 08:47 UTC, seamuslee001 commented on CRM/Utils/System/Drupal.php
> +   	$config = CRM_Core_Config::singleton();
I think it could be improved with $baseUrl = CRM_Core_Config::singleton()->userFrameworkBaseURL;

2016-08-30 15:59 UTC, garethdylan361 commented
Made improvements. Thank you for the input!

2016-08-30 16:00 UTC, garethdylan361 commented on CRM/Utils/System/Drupal.php
> +   	$config = CRM_Core_Config::singleton();
made improvements. Thank you for the input!

2016-08-30 21:14 UTC, totten commented
jenkins, ok to test

2016-08-30 21:19 UTC, garethdylan361 commented
replaced tabs with space indents

2016-09-29 23:24 UTC, colemanw requested changes
This appears to be passing a complete `http://...` url string into the drupal `url` function. I'm not sure that will work with clean urls disabled. I suspect the better way to do it would be by setting the `absolute` flag to true. Note that the function was being incorrectly used (a third param `TRUE` was being passed in but it only accepts 2 params.

2016-10-24 01:50 UTC, eileenmcnaughton commented on CRM/Utils/System/Drupal.php
> +   	$config = CRM_Core_Config::singleton();
Actually - sorry to come late to the party but - shouldn't we be passing the 'absolute' param to the drupal function?

https://api.drupal.org/api/drupal/includes!common.inc/function/url/7.x

2016-11-13 20:00 UTC, colemanw commented
@garethdylan361 can you please check the above?

2016-12-01 13:14 UTC, jitendrapurohit commented
@colemanw @garethdylan361 I've raised a new PR at https://github.com/civicrm/civicrm-core/pull/9479. Also checked by enabling/disabling clean urls and it worked fine for me.

2017-01-09 01:05 UTC, closed without merging