allow external id for custom fields import
civicrm/civicrm-core pull request #8972
Opened 2016-09-01 21:39 UTC by liedekef

2016-09-01 21:57 UTC, seamuslee001 commented on CRM/Custom/Import/Form/MapField.php
> +//  protected $_highlightedFields = array();
Not sure why this is commented out 

I would have thought later down you could have done $this->_highlightedfields[] = ... and left the page assignment to $this->_highlightedfields.

2016-09-01 22:21 UTC, liedekef commented on CRM/Custom/Import/Form/MapField.php
> +//  protected $_highlightedFields = array();
I just looked how it was done in Contact import and tried to stay in line with that code.

2016-09-02 15:00 UTC, liedekef commented on CRM/Custom/Import/Form/MapField.php
> +//  protected $_highlightedFields = array();
If you like to see this differently, I can change it of course. I'll fix the styling issues already

2016-09-25 23:41 UTC, colemanw approved these changes
Code looks good to me; haven't tested the functionality.

2016-10-06 13:13 UTC, monishdeb requested changes

2016-10-06 13:13 UTC, monishdeb commented on CRM/Custom/Import/Form/MapField.php
> +    $highlightedFields[] = 'external_identifier';
@liedekef can be optimise into 
```
 $highlightedFields = array('contact_id', 'external_identifier');
```

2016-10-06 13:13 UTC, monishdeb commented on CRM/Custom/Import/Form/MapField.php
> +        $errors['_qf_default'] .= ts('Missing required field: %1', array(1 => ts('Contact ID')));
Should we change it to 
```
ts('Missing required field: %1', array(1 => ts('Contact ID or External Identifier')));
```
 ?

2016-10-06 13:41 UTC, monishdeb commented
Although it is not related to the changes, but found another strict warning 
![image](https://cloud.githubusercontent.com/assets/3735621/19154544/9592b6d2-8bf8-11e6-8e40-434b1956d81f.png)

Will submit a PR for it later

2016-10-06 14:04 UTC, liedekef commented on CRM/Custom/Import/Form/MapField.php
> +    $highlightedFields[] = 'external_identifier';
I agree, but again: I just the same form from the contact import code. Do you want me to change it here already?

2016-10-06 14:04 UTC, liedekef commented on CRM/Custom/Import/Form/MapField.php
> +        $errors['_qf_default'] .= ts('Missing required field: %1', array(1 => ts('Contact ID')));
It's the same remark I made above :-) But indeed, I agree. Should I change it?

2016-10-06 14:05 UTC, liedekef commented
For that strict-warning, I opened a ticket in the past but got no reaction to it.

2016-10-06 14:14 UTC, monishdeb commented
@liedekef when you override a parent class function (as in here ```CRM_Custom_Import_Parser::run(...)``` ) we need to ensure that the function parameters are same in number and type as of parent function parameters (as in here ```CRM_Contact_Import_Parser::run(...)``` ). And on function parameters mismatch it throws such kind of notice, however not fatal in nature. Here the fix that we need to ensure the parameter match  and ofcourse bring changes in the function definition too. Would you now like to submit a patch for it ? and what is the ticket number ?

2016-10-06 14:27 UTC, monishdeb commented on CRM/Custom/Import/Form/MapField.php
> +        $errors['_qf_default'] .= ts('Missing required field: %1', array(1 => ts('Contact ID')));
ya sure go ahead

2016-10-06 14:27 UTC, monishdeb commented on CRM/Custom/Import/Form/MapField.php
> +    $highlightedFields[] = 'external_identifier';
Yes please :)

2016-10-06 15:10 UTC, liedekef commented on CRM/Custom/Import/Form/MapField.php
> +        $errors['_qf_default'] .= ts('Missing required field: %1', array(1 => ts('Contact ID')));
I changed "upstream" by "customfields", but for the rest I followed your steps and it should be ok now :-)

2016-10-06 15:13 UTC, liedekef commented
I new the strict-warning was related to the number of parameters, but not really a bug. But currently I don't feel confident to correct that. But the ticket number is: CRM-19281

2016-10-06 16:53 UTC, monishdeb approved these changes

2016-10-06 16:55 UTC, monishdeb commented
@liedekef thanks for your additional fix. Tested the patch, works like a charm :)

2016-10-06 16:55 UTC, merged