CRM-19313 - Can't assign custom group to relationships with two contact subtypes involved
civicrm/civicrm-core pull request #8986
Opened 2016-09-05 14:49 UTC by francescbassas

2016-09-06 19:42 UTC, totten commented
The reported test failure, `CivicrmUpgradeTest.4_2_9-multilingual_af_bg_en_mysql_bz2`, is a pre-existing issue unrelated to this PR.

2016-09-06 19:48 UTC, totten commented
jenkins, test this please

2016-09-29 19:38 UTC, colemanw requested changes
Unfortunately this now has merge conflicts. Do you mind rebasing it?

2016-09-29 19:38 UTC, colemanw commented on CRM/Custom/Form/Group.php
> +        FALSE, 'label', TRUE, array($subType)
Did you mean to do `(array) $subType` instead? This will place the variable into an array even if it is an array already.

2016-09-29 20:06 UTC, francescbassas commented
@colemanw I think that I can't rebase it GitHub says; _"This branch has conflicts that must be resolved
Only those with write access to this repository can merge pull requests."_

2016-09-29 21:25 UTC, seamuslee001 commented
@francescbassas you can so get your branch checked out locally, do a git fetch (core repo alias)
then a git rebase -i (core repo alias)/master
fix any merge issues with git mergetool (probably best)
once you have successfully rebased do git push (your repo alias) (branch name) -f

2016-09-30 07:47 UTC, francescbassas commented on CRM/Custom/Form/Group.php
> +        FALSE, 'label', TRUE, array($subType)
Thanks. This isn't necessary in current master.

2016-10-18 14:17 UTC, mlutfy commented
jenkins, test this please

2016-10-18 14:19 UTC, mlutfy commented
jenkins, test this please

2016-10-18 14:20 UTC, mlutfy commented
```
  error: patch failed: CRM/Custom/Form/Group.php:220                                 
  error: CRM/Custom/Form/Group.php: patch does not apply                             
  error: patch failed: CRM/Custom/Form/Group.php:220                                 
  error: CRM/Custom/Form/Group.php: patch does not apply                             
```

2016-10-18 15:08 UTC, francescbassas commented
Strange error. I'm no touching this file in the PR. Better if I create a new PR?

2016-10-18 19:56 UTC, colemanw commented
Yes please.

2016-10-18 19:56 UTC, closed without merging