CRM-19302 - Fix Copying of File Custom Fields on Event Copy
civicrm/civicrm-core pull request #8988
Opened 2016-09-06 06:19 UTC by MiyaNoctem

Fixed bug! Created new static method that copies all custom fields from old event to new event.  Files are handled by copying them and having separate records in civicrm_file table, not just custom fields table.

2016-09-06 06:19 UTC, civicrm-builder commented
Can one of the admins verify this patch?

2016-09-09 08:05 UTC, seamuslee001 commented on CRM/Event/BAO/Event.php
> +      throw new CRM_Core_Exception(ts('Deferred revenue account is not configured for selected financial type. Please have an administrator set up the deferred revenue account at Administer > CiviCon
won't the validateFinancialType already throw and exception? also not sure why your removing the !empty that is around it.

2016-09-27 14:49 UTC, MiyaNoctem commented on CRM/Event/BAO/Event.php
> +      throw new CRM_Core_Exception(ts('Deferred revenue account is not configured for selected financial type. Please have an administrator set up the deferred revenue account at Administer > CiviCon
Actually, that's not part of the code I fixed, but it was on the source I worked on... seems to be related to bug report 16189, not really sure how that got there, though...

2016-09-29 23:56 UTC, colemanw commented
@civicrm-builder add to whitelist

2016-09-29 23:57 UTC, colemanw requested changes

2016-09-29 23:57 UTC, colemanw commented on CRM/Event/BAO/Event.php
> +      throw new CRM_Core_Exception(ts('Deferred revenue account is not configured for selected financial type. Please have an administrator set up the deferred revenue account at Administer > CiviCon
@MiyaNoctem could you please update this PR with only the changes you meant to make?

2016-10-05 19:24 UTC, colemanw commented on CRM/Event/BAO/Event.php
>      );
This block seems to do the same thing as the above?

2016-11-17 10:39 UTC, Edzelopez commented
Tested patch on 4.7, works fine.

2016-11-17 10:46 UTC, monishdeb commented
Jenkin test this please

2016-11-17 12:01 UTC, monishdeb commented
Closed in favor of https://github.com/civicrm/civicrm-core/pull/9407

2016-11-17 12:01 UTC, closed without merging