CRM-19353 - 'Dedupe by email' not working 2
civicrm/civicrm-core pull request #9059
Opened 2016-09-16 17:42 UTC by hakuren

[CRM-19353: 'Dedupe by email' not working](https://issues.civicrm.org/jira/browse/CRM-19353)

2016-09-16 17:42 UTC, civicrm-builder commented
Can one of the admins verify this patch?

2016-09-26 21:33 UTC, colemanw commented
@civicrm-builder add to whitelist

2016-09-26 21:34 UTC, colemanw requested changes
This needs a couple of [style fixes](https://test.civicrm.org/job/CiviCRM-Core-PR/11828/checkstyleResult/new).

2016-09-29 21:57 UTC, eileenmcnaughton commented
test this please

2016-09-29 21:59 UTC, seamuslee001 commented
Jenkins re test this please

2016-09-29 22:01 UTC, seamuslee001 commented on CRM/Contact/BAO/Query.php
> +    if(!empty($groupBy)) {
@hakuren you need to do if ( not if(

2016-10-11 21:40 UTC, eileenmcnaughton commented
We discussed this at the sprint & we had some concerns

1) this was adding a new parameter to the api & to the api architecture ('group_by') and we weren't comfortable with that being added in an undiscussed, untested way
2) We weren't convinced the UI implied that test recipients would be deduped

I'm going to close this PR because it is against an out of date RC.

I'd encourage you to open a new ticket for the outstanding issue around test recipients being deduped, since I think #9214 resolved CRM-19353 - (unless you no longer care)

Are you on the dev email list? It would be a good place to discuss adding group_by to the api?

2016-10-11 21:40 UTC, closed without merging