Fixed: CRM-19303
civicrm/civicrm-core pull request #9088
Opened 2016-09-22 06:39 UTC by MiltoxBeyond

Single Merge

Instead of assuming the default folder exists, it checks, if not it will search nearby directories for the files.

2016-09-22 06:39 UTC, civicrm-builder commented
Can one of the admins verify this patch?

2016-09-26 20:19 UTC, colemanw commented
@civicrm-builder add to whitelist

2016-09-26 20:24 UTC, colemanw requested changes
Code looks good to me. I haven't tested the functionality.

2016-09-26 20:24 UTC, colemanw approved these changes

2016-09-26 21:23 UTC, colemanw requested changes
Actually this can't be merged until the [code style problems](https://test.civicrm.org/job/CiviCRM-Core-PR/11819/) are resolved.

2016-09-27 03:44 UTC, MiltoxBeyond commented
Style changes committed.  Fixed all warnings.

2016-09-27 15:11 UTC, colemanw commented
@civicrm-builder test this please

2016-09-29 19:05 UTC, colemanw commented
@civicrm-builder test this please

2016-09-29 22:45 UTC, seamuslee001 commented
Jenkins re test this please

2016-09-29 23:27 UTC, seamuslee001 commented
@MiltoxBeyond we are getting an error RuntimeException: Cannot resolve path using "civicrm.files.url" in Civi\Core\Paths->getVariable() (line 83 of /home/jenkins/buildkit/build/core-9088-7x4bp/sites/all/modules/civicrm/Civi/Core/Paths.php. I suspect this is related to your PR

2016-09-29 23:37 UTC, MiltoxBeyond commented
Do you have a stack trace for that error so I can track it down?  I only
added an extra check when the path doesn't exist otherwise it returns the
same values.
On Sep 29, 2016 6:27 PM, "Seamus Lee" <notifications@github.com> wrote:

> @MiltoxBeyond <https://github.com/MiltoxBeyond> we are getting an error
> RuntimeException: Cannot resolve path using "civicrm.files.url" in
> Civi\Core\Paths->getVariable() (line 83 of
> /home/jenkins/buildkit/build/core-9088-7x4bp/sites/all/modules/civicrm/Civi/Core/Paths.php.
> I suspect this is related to your PR
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/civicrm/civicrm-core/pull/9088#issuecomment-250620505>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHWTNVby-sGZ08SIlLTN3wHPznP-WsjXks5qvElMgaJpZM4KDklG>
> .
>

2016-10-05 10:21 UTC, monishdeb commented
@MiltoxBeyond here's the stacktrace 
```
WD menu: RuntimeException: Cannot resolve path using                     [error]
"civicrm.files.url" in Civi\Core\Paths->getVariable() (line 83 of
/home/jenkins/buildkit/build/core-9088-7x4bp/sites/all/modules/civicrm/Civi/Core/Paths.php).
WD php: RuntimeException: Cannot resolve path using                      [error]
"civicrm.files.url" in Civi\Core\Paths->getVariable() (line 83 of
/home/jenkins/buildkit/build/core-9088-7x4bp/sites/all/modules/civicrm/Civi/Core/Paths.php).
Cannot modify header information - headers already sent by (output     [warning]
started at
/home/jenkins/buildkit/vendor/drush/drush/includes/output.inc:38)
bootstrap.inc:1471
RuntimeException: Cannot resolve path using "civicrm.files.url" in Civi\Core\Paths->getVariable() (line 83 of /home/jenkins/buildkit/build/core-9088-7x4bp/sites/all/modules/civicrm/Civi/Core/Paths.php).
Drush command terminated abnormally due to an unrecoverable error.       [error]
```

For detail see related test build console https://test.civicrm.org/job/CiviCRM-Core-PR/11931/console

2016-10-14 09:02 UTC, seamuslee001 commented
Jenkins re test this please

2016-10-14 09:11 UTC, seamuslee001 commented on CRM/Utils/System/DrupalBase.php
> +    }
@MiltoxBeyond you need to return something from this function if $this->filesUrl is not set 

so what i have tested and seems to work is adding in at the end here 

```php
  $this->filesUrl = self::getUrl($basepath, $correct);
  return $this->filesUrl;
```

2016-10-29 02:21 UTC, colemanw commented on CRM/Utils/System/DrupalBase.php
> +    }
@MiltoxBeyond looks like the above is holding up this PR.

2016-11-21 21:08 UTC, eileenmcnaughton commented
closing as replaced by #9409

2016-11-21 21:08 UTC, closed without merging