CRM-19337 - Contact summary report
civicrm/civicrm-core pull request #9105
Opened 2016-09-25 15:07 UTC by gsm-in

When contact sub-type was included in the report, it was displaying the sub-type as **contact_sub_type from civicrm_contact** table instead of **label from civicrm_contact_type** table as being displayed on the contact summary page.

2016-09-25 15:07 UTC, civicrm-builder commented
Can one of the admins verify this patch?

2016-09-25 15:21 UTC, gsm-in commented
yes please

2016-09-26 21:16 UTC, colemanw requested changes
It looks like you are changing two methods (`getBasicContactFields` and `getBasicContactFilters`) which are used in several places, but only updated one of the reports that uses those methods. How will the others be affected?

2016-09-27 06:28 UTC, gsm-in commented
These two methods are also being used in the following files:

1. CRM/Report/Form/Event/ParticipantListing.php
2. CRM/Report/Form/Member/Detail.php
3. CRM/Report/Form/Contribute/Summary.php
4. CRM/Report/Form/Contribute/Detail.php
5. CRM/Report/Form/Contribute/Lybunt.php
6. CRM/Report/Form/Contact/CurrentEmployer.php
7. CRM/Report/Form/Contact/Detail.php

If you think the changes done earlier to _CRM/Report/Form/Contact/Summary.php_ is the correct way, I can do the same in the other files. Please confirm if I should proceed with the changes.

2016-09-27 16:22 UTC, colemanw commented
@totten any idea why this test build is crashing?

2016-09-28 15:12 UTC, colemanw commented
@civicrm-builder retest this please

2016-09-28 18:45 UTC, colemanw commented
@gsm-in our nitpicker found the following code style issues:

> Form.php:4457, CommaLastItem, Priority: Normal
> A comma should follow the last multiline array item. Found: )
> 
> Form.php:4471, CommaLastItem, Priority: Normal
> A comma should follow the last multiline array item. Found: )
> 
> Summary.php:114, CommaLastItem, Priority: Normal
> A comma should follow the last multiline array item. Found: )

2016-10-10 23:40 UTC, colemanw commented
@gsm-in could you please update this PR with the requested changes?

2016-10-11 10:58 UTC, gsm-in commented
@colemanw I'll update it soon

2016-10-11 16:31 UTC, eileenmcnaughton commented
Hi,

I just did a replacement PR - https://github.com/civicrm/civicrm-core/pull/9212 - I'm going to close this in favour of that

2016-10-11 16:31 UTC, closed without merging