IncludeSmartGroups Option added
civicrm/civicrm-core pull request #9156
Opened 2016-10-01 14:27 UTC by jainabhishek14

Added a new parameter "includeSmartGroups" for getContactGroups to include smart groups in the result.

2016-10-01 14:27 UTC, civicrm-builder commented
Can one of the admins verify this patch?

2016-10-03 22:57 UTC, jainabhishek14 commented
I am really sorry, if this would be dumbest question? Can i know the status of this patch?

2016-10-03 23:11 UTC, seamuslee001 commented
Well its in the list for review. Someone will eventually review it.

2016-10-05 09:57 UTC, monishdeb commented
@tschuettler @jainabhishek14 I think this PR provide a better solution over https://github.com/civicrm/civicrm-core/pull/9149 as per your discussion. Reason why I have added the ticket number in title. So should I close https://github.com/civicrm/civicrm-core/pull/9149 ?

2016-10-05 10:07 UTC, tschuettler commented
Yes, that's fine with me.

2016-10-05 10:13 UTC, monishdeb commented
Ok closed https://github.com/civicrm/civicrm-core/pull/9149

2016-10-05 10:14 UTC, monishdeb commented
Jenkins ok to test

2016-10-06 06:35 UTC, jainabhishek14 commented
build error was:
[xUnit] [ERROR] - No test reports found for the metric 'JUnit' with the resolved pattern 'junit/*.xml'. Configuration error?.

is it test case undefined issue?

2016-10-06 10:44 UTC, monishdeb commented
@jainabhishek14 sorry didn't have any idea about that BUT as per the test build you got 11 style errors which need to be fixed these are : 

- GroupContact.php:344, TabsUsed, Priority: High
Spaces must be used to indent lines; tabs are not allowed

- GroupContact.php:362, ControlSignature, Priority: High
Expected "if (...) {\n"; found "if(...){\n"

- GroupContact.php:362, IncorrectExact, Priority: High
Line indented incorrectly; expected 4 spaces, found 1

- GroupContact.php:362, TabsUsed, Priority: High
Spaces must be used to indent lines; tabs are not allowed

- GroupContact.php:363, TabsUsed, Priority: High
Spaces must be used to indent lines; tabs are not allowed

- GroupContact.php:363, IncorrectExact, Priority: High
Line indented incorrectly; expected 6 spaces, found 2

- GroupContact.php:364, IncorrectExact, Priority: High
Line indented incorrectly; expected 2 spaces, found 1

- GroupContact.php:364, TabsUsed, Priority: High
Spaces must be used to indent lines; tabs are not allowed

- GroupContact.php:365, EndLine, Priority: High
Whitespace found at end of line

- GroupContact.php:366, IncorrectExact, Priority: High
Line indented incorrectly; expected 2 spaces, found 4

- GroupContact.php:367, IncorrectExact, Priority: High
Line indented incorrectly; expected 4 spaces, found 6

For detail https://test.civicrm.org/job/CiviCRM-Core-PR/12001/checkstyleResult/new/

2016-10-08 21:24 UTC, jainabhishek14 commented
@monishdeb I have fixed the style errors. Should I create a new pull request or modify this one?

2016-10-08 21:25 UTC, seamuslee001 commented
@jainabhishek14 just push to the same branch as this PR

2016-10-08 21:26 UTC, jainabhishek14 commented
@seamuslee001 I already pushed the fix but it does not reflect here..

2016-10-08 21:27 UTC, seamuslee001 commented
@jainabhishek14 was it on the same branch the CRM-19435 branch?

2016-10-08 21:28 UTC, jainabhishek14 commented
@seamuslee001 yes

2016-10-08 21:31 UTC, seamuslee001 commented
I see the commit here now not sure why it wasn't there before and its past the style checker and onto the test suite.

2016-10-08 21:33 UTC, jainabhishek14 commented
@seamuslee001 Thanks, I can see it now...
also could you also help me what does "[xUnit] [ERROR] - No test reports found for the metric 'JUnit' with the resolved pattern 'junit/*.xml'. Configuration error?." mean?

2016-10-08 21:37 UTC, seamuslee001 commented
@jainabhishek14 That was from your first test run the 2nd one is here https://test.civicrm.org/job/CiviCRM-Core-PR/12050 (there is currently an orange circle next to your 2nd commit which indicates test is running)

2016-10-08 21:42 UTC, jainabhishek14 commented
Thank you very much @seamuslee001 for the information.

2016-10-12 12:42 UTC, monishdeb commented
Before 
![image](https://cloud.githubusercontent.com/assets/3735621/19310358/486b0f4a-90a7-11e6-82f5-45dcbb5161b0.png)

After 
![image](https://cloud.githubusercontent.com/assets/3735621/19310366/56cdbe8e-90a7-11e6-8be4-347fb8ab84d0.png)

2016-10-12 12:46 UTC, monishdeb requested changes

2016-10-12 12:46 UTC, monishdeb commented on CRM/Contact/BAO/GroupContact.php
> +    $includeSmartGroups = FALSE
@jainabhishek14 you need to also document the new parameter ```$includeSmartGroups``` in the function description as 
```
 @param bool $includeSmartGroups 
                     [short description]
```
Everything else is working fine :)

2016-10-13 05:08 UTC, monishdeb commented
Anyways I am merging this  PR and will submit a separate PR for the mentioned change.

2016-10-13 05:09 UTC, merged