[ready-for-core-team-review]CRM-19485, Fixed selector issue on Batch Transaction form
civicrm/civicrm-core pull request #9211
Opened 2016-10-11 15:26 UTC by pradpnayak

----------------------------------------
* CRM-19485: Selector issue on Batch trxn assignment page
  https://issues.civicrm.org/jira/browse/CRM-19485

2016-10-12 15:24 UTC, JoeMurray commented
I've tested successfully and reviewed code. Ready to merge.

2016-10-12 22:09 UTC, colemanw requested changes

2016-10-12 22:09 UTC, colemanw commented on templates/CRM/Financial/Form/BatchTransaction.tpl
> +toggleFinancialSelections('#toggleSelect', 'assign');
Disabling async in ajax calls is deprecated.
Add this call to your fnCallback instead and you don't need to do so. Like this:

    "success": function() {
      toggleFinancialSelections('#toggleSelect', 'assign');
      fnCallback();
    }

2016-10-12 22:09 UTC, colemanw commented on templates/CRM/Financial/Form/BatchTransaction.tpl
> +toggleFinancialSelections('#toggleSelects', 'remove');
Ditto.

2016-10-12 22:09 UTC, colemanw commented on templates/CRM/Financial/Form/BatchTransaction.tpl
> +  mark = 'x';
missing `var` keyword

2016-10-12 22:09 UTC, colemanw commented on templates/CRM/Financial/Form/BatchTransaction.tpl
> +          </tr>
was this missing previously?

2016-10-20 13:14 UTC, pradpnayak commented on templates/CRM/Financial/Form/BatchTransaction.tpl
> +          </tr>
Yes, it was missing

2016-10-20 13:16 UTC, pradpnayak commented
@colemanw thanks for the alternate solution for async. I have updated the PR with the changes. Could you please review?

2016-10-20 14:41 UTC, colemanw approved these changes

2016-10-20 14:42 UTC, merged