bootstrap styles being applied to labels on the backend in joomla
civicrm/civicrm-core pull request #9365
Opened 2016-11-08 23:48 UTC by alifrumin

Joomla uses bootstrap (http://getbootstrap.com/) on the backend to style things and the bootstrap styles of labels overide civiCRM's styling of labels and make labels into little inline pill like things, this resets the styling to the civi version of what a label is (only on civi pages)

2016-11-13 15:30 UTC, colemanw requested changes

2016-11-13 15:30 UTC, colemanw commented on css/joomla.css
> +#crm-container .label {
Using the class selector `.crm-container` will include popups. The id selector `#crm-container` is only for the main content area.

2016-11-13 15:30 UTC, colemanw commented on css/joomla.css
> +#crm-container .crm-container .form-layout td.label {
I think this should be on two lines to get both cases, like 

    #crm-container .form-layout td.label,
    .crm-container .form-layout td.label {

2016-11-15 18:45 UTC, alifrumin commented
Thank you for the tips @colemanw, I made the changes you suggested.

2016-11-15 19:19 UTC, colemanw approved these changes

2016-11-15 19:20 UTC, merged