CRM-19585, fixed code for retrieving last financial item for contribu…
civicrm/civicrm-core pull request #9589
Opened 2016-12-28 22:09 UTC by pradpnayak

…tion

----------------------------------------
* CRM-19585: Sales tax issue
  https://issues.civicrm.org/jira/browse/CRM-19585

2016-12-29 00:09 UTC, pradpnayak commented
depends on https://github.com/civicrm/civicrm-core/pull/9590

2016-12-30 11:46 UTC, pradpnayak commented
jenkins, retest this please

2017-01-19 20:23 UTC, coldrunKacper commented
Looks fine to me. Approved.

2017-01-23 08:18 UTC, pradpnayak commented
Can this be merged?

2017-03-08 22:14 UTC, eileenmcnaughton requested changes
OK, so here is my problem with this one
1) I don't know what problem it's trying to fix, it doesn't have it's own JIRA ticket & there is nothing to explain how to replicate any problem
2) I don't know what was reviewed - code only , or the actual bug.

OTOH I agree the code looks good & the test coverage is good.

Can we get the administrative side of this tidied up.

2017-03-10 07:13 UTC, eileenmcnaughton commented
per other comments, setting to WIP to get a clear ticket that this relates to & steps to replicate

2017-03-13 14:59 UTC, JoeMurray commented
Pradeep will be updating the administrative side. I think it would be good for there to be an indication that testing has actually worked once the issue description of problem is provided.

2017-03-14 11:12 UTC, pradpnayak commented
Created ticket at https://issues.civicrm.org/jira/browse/CRM-20260 and added steps to replicate

2017-03-14 19:06 UTC, JoeMurray commented on CRM/Financial/BAO/FinancialItem.php
> +    $liabilityAccountType = CRM_Core_OptionGroup::getValue('financial_account_type', 'Liability', 'name');
You need to provide some code comments here to explain what you are doing with Liability Type financial accounts.

2017-03-14 19:09 UTC, JoeMurray commented on CRM/Financial/BAO/FinancialItem.php
>        1 => array($entityId, 'Integer'),
throughout system entity_table always is entered in schema before entity_id. Stylistically would be nice to keep that order.

2017-03-14 19:19 UTC, JoeMurray commented on CRM/Financial/BAO/FinancialItem.php
> +            AND cfi.financial_account_id  = from_financial_account_id
You should put table alias or table name before from_financial_account_id.

2017-03-14 19:20 UTC, JoeMurray commented on CRM/Financial/BAO/FinancialItem.php
> +          WHEN cfa.financial_account_type_id = %3
Why not simplify by replacing CASE with ((cfa.financial_account_type_id = %3 AND cfi.financial_account_id  = from_financial_account_id) OR financial_account_type_id <> %3)

2017-03-14 19:20 UTC, JoeMurray commented on CRM/Financial/BAO/FinancialItem.php
> +    $query = 'SELECT cfi.id, cfi.description, cfi.amount, cfi.financial_account_id, cfi.status_id
I don't understand why you're only choosing these fields. Don't you need to copy contact_id and currency to new financial_item? What about *

2017-03-15 07:32 UTC, eileenmcnaughton commented on CRM/Financial/BAO/FinancialItem.php
> +    $liabilityAccountType = CRM_Core_OptionGroup::getValue('financial_account_type', 'Liability', 'name');
Note that function is deprecated - if you use an IDE like php storm that leaps out at you.

![screenshot 2017-03-15 20 31 07](https://cloud.githubusercontent.com/assets/336308/23937825/5f90058c-09be-11e7-960b-bc76cb775d96.png)

I believe in more cases you can do things with 

CRM_Core_PseudoConstant::getLabel()
CRM_Core_PseudoConstant::getKey()
CRM_Core_Pseudoconstant::getName()

2017-03-15 11:59 UTC, eileenmcnaughton commented
@pradpnayak with those instructions I was able to replicate the bug & confirm your changes fixed it.

However, the code that this touches on is pretty nasty & I wasn't able to verify it without going through the full process I would go through to fix the  bug - ie. writing a unit test that fails & then fixing the code until it passes. In the process I would up with an alternate fix. Although it looks longer
https://github.com/civicrm/civicrm-core/pull/9984 I think most of the extra length is in the full-flow-test and the fact I renamed a few variables & function names. The actual key function is shorter and I was able to remove the sql from it (ideally we would have a lot less sql in the codebase).

I tried to comment it really heavily in github so you could make sense of it & review it, let me know.

I also logged a follow on bug that I identified & linked to a fix from JIRA https://issues.civicrm.org/jira/browse/CRM-20276  - that fix depends on my PR & needs to be reviewed after this one is resolved

2017-04-10 09:24 UTC, monishdeb commented
@JoeMurray @eileenmcnaughton I have made the desired changes requested in the PR and tested.

2017-04-10 15:41 UTC, colemanw commented
@eileenmcnaughton do these latest changes look good to you?

2017-04-11 02:10 UTC, eileenmcnaughton commented
@pradpnayak I pulled your test into #9984 to see if it would still pass with the simpler api-based method and it's passing! (note I changed it a little since you did your QA). Do you think there is still a scenario #9984 is not working with or should we merge that one (which has other improvements / additional tests  / less in-code sql)

2017-04-25 09:23 UTC, eileenmcnaughton commented
I order to unblock this and the follow on bug fix I have merged #9984 and am closing this.

I understand that there is still a use-case that needs a test & which will alter the merged fix, that affects users of deferred_revenue under some config. I would not have merged the other had we not just cut the rc.  

This has been really stalled & hard to get clarity on so getting to a clear point on what has been merged seems like a priority to me

2017-04-25 09:23 UTC, closed without merging