Checked in for CRM20147. Wrong array indexing
civicrm/civicrm-core pull request #9868
Opened 2017-02-21 11:01 UTC by VasanthaKaje

As the array was trying to be indexed by another array, changed it to be indexed by a String - in the same lines as it behaves in Civicrm for D7. Confirmed it to be working

2017-02-21 11:02 UTC, civicrm-builder commented
Can one of the admins verify this patch?

2017-02-25 23:19 UTC, jackrabbithanna commented
I confirmed the issue, and confirmed that this PR fixes it
@colemanw thoughts about merging?

2017-03-08 07:09 UTC, eileenmcnaughton requested changes
Per my comments, I think this should have an IF to preserve prior behaviour, as I think it will cause regressions in some cases. Would also need code comments

2017-03-09 02:52 UTC, colemanw commented
@VasanthaKaje can you update the PR according to Eileen's review?

2017-03-16 04:03 UTC, eileenmcnaughton commented
please remove the wip when ready for re-review

2017-12-01 22:31 UTC, closed without merging

2019-04-25 16:53 UTC, johncronan commented
I see this warning on our site too. I think the code should be fixed. In any case, I'll add this one to my set of custom patches, since there's no concern about how it works with D8.